### ISSUE TITLE
webpack-stats.json is not updated in dev mode

### ISSUE THREAD

**Issue by jaulz** [iam4x/isomorphic-flux-boilerplate#10]
The webpack-stats.json file still contains the entries from the previous `npm run build` and thus the wrong javascript files are loaded.

**Comment by iam4x** [comment]
Can you check if `write-stats.js` is called with `$ npm run dev` ?

Add on line 32 (https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/webpack%2Futils%2Fwrite-stats.js#L32):

```
console.log('webpack-stats.json: ', content);
```

Maybe it's failing somewhere else hard to tell from your message.

**Comment by jaulz** [comment]
Okay, it had some side effects because of my cloud9 landscape. I created a fork now and added the possibility to operate only on one external port:
https://github.com/jaulz/isomorphic-flux-boilerplate/commit/a78ab90d651476d7c3a924d871684f1e3cacf51b

If you have any comments, let me know and I'll see how to update it accordingly.

**Comment by iam4x** [comment]
Does Cloud9 editor expose an env variable to know you are using Cloud9? You could check for this and merge it!

**Comment by jaulz** [comment]
Yes, there is: process.env.C9_HOSTNAME
PR will follow
