### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by seemsindie** [iam4x/isomorphic-flux-boilerplate#107]
Hello guys, i get this error on npm install, and i am unable to run npm run dev afterwards.

https://gist.github.com/seemsindie/d2a0ec7ef6d0556aa1a6

My node(iojs) version is v3.1.0 and npm 2.13.3

Thanks.

**Comment by seemsindie** [comment]
To answer my own issue, i downgraded iojs version to v2.3.3 and it worked.

**Comment by dmitry** [comment]
I had the same issue with >= 3.x, with 2.5.0 everything works fine.
