### ISSUE TITLE
react-router BrowserHistory error

### ISSUE THREAD

**Issue by seemsindie** [iam4x/isomorphic-flux-boilerplate#109]
When i clone the repo, do an npm install and run npm run dev, i get the following error:

    ERROR in ./app/main.js
    Module not found: Error: Cannot resolve module 'react-router/lib/BrowserHistory' in     /home/ivan/Projects/Personal/testapp/app
     @ ./app/main.js 23:36-78

Any idea why is this happening?

**Comment by dmitry** [comment]
@seemsindie what version of the react-router do you have? (the latest is v1.0.0-beta4 was released just 9 hours ago, might be an issue there)

**Comment by djbobbydrake** [comment]
Same issue for me. Looks like beta4 is using a history submodule which then makes it incompatible. If you update package.json to read `"react-router": "1.0.0-beta3"` instead of `"react-router": "^1.0.0-beta3"`, then do another npm install, and npm run dev, should work.

**Comment by seemsindie** [comment]
@dmitry Version "react-router": "^1.0.0-beta3"

**Comment by dmitry** [comment]
@seemsindie make it `"react-router": "1.0.0-beta3"` and try again :)

**Comment by seemsindie** [comment]
@dmitry I did, it works. Thanks guys.
