### ISSUE TITLE
Unable to set component defaultProps? 

### ISSUE THREAD

**Issue by thatjsguy** [iam4x/isomorphic-flux-boilerplate#110]
It might be my lack of specific understanding regarding `isomorphic-flux-boilerplate` , but I thought I would at least ask how I would achieve this in `profile.jsx`. I don't think that duplicating the component just to support a route for theoretical `currentUser` is a good idea..

## Route

```
{generateRoute({
      paths: ['/profile/:seed', '/my-profile'],
      component: require('./components/profile')
})}
```

## Component 

Here I am trying to manually set the defaultProps in case the `:seed` param is missing..

```
static defaultProps = {
    params: {
      seed: 'f60429024169712c'
    }
}
```

**Comment by iam4x** [comment]
@thatjsguy `defaultProps` won't replaced when the value is null, it only does it when it's undefined. ReactRouter pass `params: { seed: null }` or string empty. That's why.
