### ISSUE TITLE
JWT and isomorphism

### ISSUE THREAD

**Issue by djbobbydrake** [iam4x/isomorphic-flux-boilerplate#111]
I am trying to implement JWT using this boilerplate and am unsure of how to go about implementing it. I tried storing the token in localStorage, but this isn't available on the server side. Can you provide some guidance on implementing JWT?

Thanks!

**Comment by dmitry** [comment]
@djbobbydrake why not to store token in the old-school cookies?

**Comment by djbobbydrake** [comment]
@dmitry Thanks. I am implementing cookies right now. But was wondering if there's a non-cookie solution anyone else is utilizing.

**Comment by dmitry** [comment]
@djbobbydrake there are only URI query and cookie states are shared between browser / server. As I know nothing else is possible, except some really exotic, like flash.

**Comment by djbobbydrake** [comment]
@dmitry I'm a bit new to using koa and with react-js in general. Is there a way to read cookies on the server side in a synchronous way? I'm trying to check for a valid token, then redirect the user to a logged in page. However, the way that I have things set up, the non-logged-in page loads for a split second before the client-side js takes over and properly redirects the user. How do I prevent that initial page load that is rendered by the server.  In other words, I'd like to move the check for the cookie to the server side, but am not quite sure how to go about doing that.  Any help is appreciated.

**Comment by cridenour** [comment]
@djbobbydrake I have done this in our own project. When you set up your store, the key is to just read from the cookie on koa and set your store before any rendering.


In server/router.jsx

```javascript
  // Init alt instance
  const flux = new Flux();

  // Get the JWT
  const jwt = this.cookies.get('_jwt') || '';

  // Set our authentication
  if (jwt != '') {
    debug('dev')(`Authenticating user with token: ${jwt}`);

    flux
    .getActions('authentication')
    .restoreSession(jwt);
  } else {
    debug('dev')(`Anonymous request`);
  }
```

**Comment by djbobbydrake** [comment]
Awesome @cridenour. That approach is working for me.

**Comment by djbobbydrake** [comment]
Actually @cridenour I have another question about that. Where do you implement the redirect. I'm currently doing it on the component at componentWillMount() but that is a bit too late in the process.

**Comment by dmitry** [comment]
@djbobbydrake good source of alternative solutions to cookies (not all of them work on server and client): https://en.wikipedia.org/wiki/HTTP_cookie#Alternatives_to_cookies

**Comment by cridenour** [comment]
We don't currently have a login redirect - just an error message. We will likely end up doing a login modal rather than a server side redirect.

**Comment by djbobbydrake** [comment]
Okay, thanks fellas. Will close this out as my original question has been answered.

**Comment by utkuturunc** [comment]
What about csrf protection? Won't the server be vulnarable to csrf attacks if the jwt is stored with cookies? How do you implement csrf protection?
