### ISSUE TITLE
react-router/lib/BrowserHistory dont exist in react-router 1.0.0-beta4

### ISSUE THREAD

**Issue by antonoberg** [iam4x/isomorphic-flux-boilerplate#112]
This can be prevented by locking react-router version to 1.0.0-beta3

**Comment by dmitry** [comment]
Make sure you have checked an issue: https://github.com/iam4x/isomorphic-flux-boilerplate/issues/109

**Comment by antonoberg** [comment]
Sorry!

**Comment by iam4x** [comment]
Fixed with #113
