### ISSUE TITLE
Windows: 'BABEL_ENV' is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by jaredkotoff** [iam4x/isomorphic-flux-boilerplate#116]
To get npm run dev on windows to work I had to rewrite the dev script in package.json to:
 `"dev": "SET BABEL_ENV=browser&&SET NODE_ENV=development&&babel-node ./webpack/dev-server.js",`

**Comment by iam4x** [comment]
@jaredkotoff I think I will add a script to set `process.env` for starting dev. This will fixes differences with windows and osx / linux.
