### ISSUE TITLE
require-auth isAuthenticated from store?

### ISSUE THREAD

**Issue by jaredkotoff** [iam4x/isomorphic-flux-boilerplate#117]
The require-auth.jsx is just hard coded to always be false.  
I realize there's a TODO here and I was wondering if someone could implement this or explain to me how I can actually use to component to check if a user is authenticated or not?  
It would be great if you could check the state of a store (I can't figure that out inside the onEnter function).

**Comment by cridenour** [comment]
Until we can start using the Alt singleton, I ended up using a global variable that is set in the store (or router.jsx if reading from a cookie) and checked in the utility. 

Simple, but it works!

**Comment by iam4x** [comment]
routes.jsx
```
export default function(flux) {

  function isConnected(nextState, transition) {
    const { user }  = flux.getStore('session').getState(); 
    if (!user) return transition.to('/login');
  } 

  return (
    <Route onEnter={ isConnected } .... />
  );
}
```

main.js
```
...
const routerProps = {
  routes: require('routes')(flux),
  history: ....
}
...
```

I have to put the example in the repo, but the logic is here to require routes as a function where you pass the flux instance. And declare your `onEnter` hooks into this function to use the Flux instance.

No need to globals.

**Comment by cridenour** [comment]
Hey this is interesting - so the flux instance is getting passed to the routes.jsx? It doesn't seem like it is attached as a prop until after the transition logic in router.jsx.

**Comment by iam4x** [comment]
With this method, you initialize the routes with flux inside. If you keep your `onEnter` hook in the scope you can access to the flux instance.

I'm a little busy at work, but I'll have to update this with a full example which works really great :+1:

**Comment by cridenour** [comment]
Oh got ya. My current onEnter is definitely outside the scope which is why I reverted to globals. I'll definitely have to adjust mine. 

Thanks!

**Comment by jchapple** [comment]
Lovely approach! Thanks. :)

**Comment by JaredKotoff** [comment]
I get `Unhandled promise rejection TypeError: transition.to is not a function` but using redirect(), like in the require-auth component, works fine. Is there a difference or something I should be aware of?

**Comment by iam4x** [comment]
@JaredKotoff You have to use `redirect()` it comes with `react-router@1.0.0-rc` :+1:

**Comment by JaredKotoff** [comment]
@iam4x  That's what i though. Just wanted to make sure (all the router changes and deprecations are confusing me). Thanks!

**Comment by jchapple** [comment]
Yes. For reference, he's my `requireAuth` function:

```javascript
function requireAuth(nextState, replaceState) {
  const { token } = flux.getStore('authentication').getState();

  if (! token) {
    replaceState({ nextPathname: nextState.location.pathname }, '/login');
  }
}
```

I also needed to modify `server/router.jsx` to call the new routes function with the flux instance, e.g.:

```javascript
// Get routes
const routes = require('routes')(flux);
```

**Comment by cridenour** [comment]
The last piece is what wasn't clicking for me - was definitely over complicating it in my head!

**Comment by JaredKotoff** [comment]
So now, wrapping my routes inside of a return() causes a ReactJS warning about differences in markup.
```
(client) <div data-reactid=".1
(server) <noscript data-reacti
```

**Comment by jchapple** [comment]
Read the second part of my comment above.

**Comment by JaredKotoff** [comment]
@jchapple oops. i saw that and just though that was the same code as the one iam4x already mentioned.

**Comment by iam4x** [comment]
I will let this open until I make the correct example in the repo.

**Comment by lovegroveandy** [comment]
It would be great to see an example in the repo as I to am struggling to get this working correctly

**Comment by jaredkotoff** [comment]
@iam4x @jchapple  this doesn't seem to work anymore with all the changes does to the repo recently. 
Any ideas?  
I still prefer this method than the component based one as its easier to tell which routes have it implemented by looking at a single file.  
I also couldn't figure out how to access flux from the requiredAuth component.
