### ISSUE TITLE
Not working with nodejs 4.1 on windows machine

### ISSUE THREAD

**Issue by ponty96** [iam4x/isomorphic-flux-boilerplate#119]
Couldn't install all packages in package.json on my windows 8.1 machine

**Comment by iam4x** [comment]
Please use nodejs-4.0.0 like https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/package.json#L148 says it :+1: 

And for windows, please check this issue also: https://github.com/iam4x/isomorphic-flux-boilerplate/issues/116
