### ISSUE TITLE
Component not updating from listening store

### ISSUE THREAD

**Issue by jaredkotoff** [iam4x/isomorphic-flux-boilerplate#121]
`components\app.jsx`
```jsx
...
constructor(props, context) {
  super(props, context);
  this.state = {
    myInfo: props.flux.getStore('user').getState().myInfo,
  };
}

componentDidMount() {
  const { flux } = this.props;
  flux.getStore('user').listen(this._handleUserChange);
}
...
_handleUserChange = (newState) => {
  return this.setState(newState);
}
...
```
I call `flux.getActions('user').fetchUserInfo(token);` inside of `router.jsx` (to see if they have a token cookie already) or after they login. This makes an API request and returns, updates the `user` store's state but the `_handleUserChange()` in `app.jsx` is never called.
I have a console.log when app.jsx is rendered and it seems to be rendered twice. At the times of both these `myInfo` is empty. 
I have another console.log inside of the store which shows that the store is populated with data but the component is never re-rendered. 

Any ideas as to what i might be doing wrong?

**Comment by jaredkotoff** [comment]
Think most of this was caused by a error on my part. Will reopen if having further issues.

**Comment by jaredkotoff** [comment]
This might be relevant: http://stackoverflow.com/questions/23800355/reactjs-why-child-components-arent-re-rendering-on-data-change

But in my case the component I'm mounting is directly in app.jsx, outside the the rendering method in the boilerplate.

**Comment by iam4x** [comment]
@jaredkotoff It's different because your handler is never called, could you setup a example github repo? I'll will check that :)

**Comment by jaredkotoff** [comment]
@iam4x i added you as a contributor to a stripped down private repo.  
i might push another issue later i'm having if you got the time to check it out.  
appreciate the help.

**Comment by iam4x** [comment]
I will close this, it's specified to your application. I've create an issue on the repo you shared me.
