### ISSUE TITLE
font-awesome fonts

### ISSUE THREAD

**Issue by arosboro** [iam4x/isomorphic-flux-boilerplate#122]
Is it possible to use font-awesome fonts?

I've made the following attempted changes, but to no success.

`npm install font-awesome --save`

webpack/dev.config.js:
```
...
config.module.loaders = config.module.loaders.concat([
  {
    test: /\.(jpe?g|png|gif|svg|woff|woff2|eot|ttf)(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'file?name=[sha512:hash:base64:7].[ext]',
  },
  {
    test: /\.css$/,
    loader: 'style!css?sourceMap!postcss'
  }
]);
...
```

webpack/utils/write-stats.js:
```
...
  const fontsRegex = /\.(woff|woff2|eot|ttf)$/;
  const fonts = json.modules
    .filter(module => fontsRegex.test(module.name))
    .map(font => {
      debug('dev')(font.name);
      debug('dev')(font.assets[0]);
      return {
        original: font.name,
        compiled: `${publicPath}${font.assets[0]}`
      };
    });

  const content = { script, style, images, fonts };
...
```

app.css:
```
...
@import 'font-awesome/css/font-awesome.css';
...
```

The fonts show up emitted as chunks, but there are no files in the dist folder, and of course font styling for font face is not applied.

**Comment by iam4x** [comment]
I will update the repo with FontAwesome, I use it also :+1:

**Comment by arosboro** [comment]
It's a little ugly but this one works: https://regex101.com/r/yY7tH6/1

**Comment by iam4x** [comment]
@arosboro Yes, I didn't went so far with my own projects. Just removed the last `$` and I didn't really had problems. As long you don't have a file called: `xxxx.woff.jsx` it should be good.

I think this is the proper way. I'll ask a co-worker pro regex if has a cleaner regex :)

**Comment by hamczu** [comment]
Have you tried to use react component instead? https://github.com/andreypopp/react-fa

**Comment by iam4x** [comment]
I've ended up with

```
{
  test: /\.(jpe?g|png|gif|svg|woff|woff2|eot|ttf)(\?v=[0-9].[0-9].[0-9])?$/,
  loader: 'file?name=[sha512:hash:base64:7].[ext]',
  exclude: /node_modules\/(?!font-awesome)/
},
```
