### ISSUE TITLE
Question: How to prevent react-router client-side page transition until all XHR promises are resolved?

### ISSUE THREAD

**Issue by jchapple** [iam4x/isomorphic-flux-boilerplate#127]
Hi folks,

I'm having a little trouble figuring out how to prevent `react-router` client-side page transitions from happening until all async data promises have been resolved. As I currently have it, I am firing actions from `componentWillMount` to retrieve the data dependencies via XHR. The problem with this is that there is a 'flickering' effect between landing on the page while the data loads, and the store / component subsequently updating with the retrieved data. It wouldn't really be right for my application to try and handle UI loading with spinners, 'loading' text within the component, etc.

I have been doubting if it would be possible at all to preemptively 'stall' the page transition with this approach, given that the component must first mount before the XHR request is even triggered. Perhaps it is the case that we must, for example, provide a static `fetchData` method within the component in order to declare its data dependencies (or at least, in this case - declaring how to retrieve them imperatively)?

I've been looking at this example here: https://github.com/rackt/react-router/issues/2101, in which the author describes the use of "a top component that sits below the router but above the app, using `componentWillReceiveProps` and `shouldComponentUpdate` to isolate the app from router changes while letting it go about its business undisturbed." I may have misunderstood this, but I'm wondering if we could somehow use that 'trick' to help here?

Has anyone had any experience with this sort of thing with async client-side fetching? Any pointers / help would be massively appreciated!

Cheers

**Comment by iam4x** [comment]
Hello @jchapple,

Have you looked into https://github.com/ericclemmons/react-resolver ? 

By the way you are right, the boilerplate isn't built in this direction, the right way is to have loading states and handle transition correctly between pages to have fluid user experience.

Home made solution: I think it would be possible to have global `onEnter` hook on routes and wait until promised are resolved: https://github.com/rackt/react-router/blob/713c2b0d2f1e0dae06456e0f74a34d32a175d7a5/modules/TransitionUtils.js#L3-L13

For getting flux state into your `onEnter` routes hook, look at my comment here: https://github.com/iam4x/isomorphic-flux-boilerplate/issues/117#issuecomment-142291655

Hope it helps!

**Comment by jchapple** [comment]
Thanks for your reply, @iam4x. 

`react-resolver` looks nifty but my gut feeling is that it might be a little difficult to integrate with this boilerplate while keeping `alt-resolver` (which I rather like) and have it all work together isomorphically.

I will have a go at the global `onEnter` solution you've kindly suggested and see how it goes. Hopefully the 'non-responsive UI' mentioneed only affects React DOM reconciliations or something, rather than blocking the browser!

**Comment by jchapple** [comment]
Just a quick update on this:

As far as I can tell, it's actually impossible to use `onEnter` to achieve the desired behaviour here. This is because, again, the `componentWillMount` hook in the component we're transitioning to isn't triggered until after the `callback` is called within `onEnter`. 

I'm going to try integrating `react-resolver` - on second look, it looks like that might not be such a challenge!

**Comment by iam4x** [comment]
Exact @jchapple you should add a static method on components where you do the async operations and taking as argument flux instance. This is how other boilerplate are doing it. 

There's maybe another way to achieve this and store react-router state into flux  using https://github.com/altjs/router (I didn't tried it yet).

**Comment by jaredkotoff** [comment]
@jchapple curious to see if you ever got react-resolver integrated and how its working for you if you did?

**Comment by jchapple** [comment]
Hi @jaredkotoff,

Haven't gotten round to trying out Relay yet - sure I will at some point though. :)

Here's my current solution using `onEnter` and taking advantage of the existing Flux async flow. You basically just trigger Flux actions that trigger XHR requests within a static `fetchData` method in the component, e.g.:

```javascript
static fetchData = flux => flux.getActions('customers').getCustomers()
```

Here's an example of the `onEnter` handler:
```javascript
function onEnterHandler(nextState, replaceState, callback) {
  function fetchDataIfNeeded() {
    const { component } = nextState.routes[1];

    if (typeof component.fetchData === 'function') {
      if (process.env.BROWSER) {
        if (! flux._resolver._firstClientSideRender) {
          // Browser: trigger fetchData and then listen to requests store changes
          component.fetchData(flux, nextState);

          if (requests.getState().inProgress) {
            RequestsActions.pageStart();

            const unlisten = requests.listen(({ inProgress }) => {
              if (! inProgress) {
                unlisten();
                setTimeout(() => {
                  callback();
                  RequestsActions.pageSuccess();
                });
              }
            });

            return;
          }
        }
      } else {
        // Server: simply fetch data and continue - promises will be handled by alt-resolver
        component.fetchData(flux, nextState);
      }
    }

    callback();
  }

  fetchDataIfNeeded();
}
```

There are a few caveats to mention:
* You must remember to always trigger the global requests store actions when doing XHR
* The implementation assumes that a component at a given depth in the component tree will be considered the 'page-level' component
* Not handling nested data dependencies
* .. a few others I can't remember, maybe

**Comment by jchapple** [comment]
I'mma close this now as this approach is working well for me.
