### ISSUE TITLE
Hot reload on any file style change

### ISSUE THREAD

**Issue by Ehesp** [iam4x/isomorphic-flux-boilerplate#129]
Currently, hot reloading only takes place when the `app/styles/app.css` changes. Changing a file such as `header.css` doesn't hot reload, and also refreshing the page does not show the updates either. I have to re-run the `dev` script to see any changes.

Anyway around this? Still getting my head around web pack at the moment.

**Comment by iam4x** [comment]
@Ehesp Yes, remove cssnext and update postcss. I might do this and use `precss` instead of `postcss`. I have a working configuration here: https://github.com/iam4x/watchdeps-menubar/blob/master/webpack/dev.config.js#L53

**Comment by iam4x** [comment]
Fixed with 085fe3f
