### ISSUE TITLE
How do I get a clean Initial index.html for pure clientside?

### ISSUE THREAD

**Issue by beckend** [iam4x/isomorphic-flux-boilerplate#131]
It would seem that a koa generator is generating the initial index page, and it's already filled with content.
Is it possible to generate clean index.html file with all only the essential main js and main css file to run entirely on the client side?

**Comment by iam4x** [comment]
This is not supported yet and it's a very specific feature, since this boilerplate is built around server side rendering of components it's not in the scope.

I can add a `--static` build option that would generate a clean index.html which just require the dist files. But this isn't my priority, you should use a static ReactJS boilerplate.

**Comment by beckend** [comment]
That's fair,
I'm kinda new to react and it's router, being an angular dev...
Could you describe what it would take to make this static build possible? I would like a shot at it.
Like how can the this react application bootstrap and initialize from an empty body?
I tried to remove the body output from "index.hbs" and keeping only the js, it didn't work so well.

**Comment by tracker1** [comment]
@backend it sounds like what you are wanting is not an isomorphic flux application?  What you are describing is a general SPA app in flux/react with no server-side rendering.

**Comment by beckend** [comment]
It actually is, the project we are doing is server-sided rendering, but must have the ability to build for the client also. We want to share as much code as possible for both ends.

**Comment by dmitry** [comment]
@beckend that's what this boilerplate is actually do. I suggest you to try-out locally and read the source. It saved me a lot of time.

**Comment by iam4x** [comment]
@beckend Oh! Clone the project and play with it, you will see that is the default behaviour. Be sure to check out: http://isomorphic.iam4x.fr as live demo.
