### ISSUE TITLE
Testing state

### ISSUE THREAD

**Issue by djbobbydrake** [iam4x/isomorphic-flux-boilerplate#134]
I am a bit confused about how to go about writing a test in which I want to test state within a component. Can someone give an example of how this can be done with the current framework?

**Comment by iam4x** [comment]
@djbobbydrake https://facebook.github.io/react/docs/test-utils.html#findrendereddomcomponentwithtag

I need to find an example of it somewhere in one of my projects.

**Comment by djbobbydrake** [comment]
Thanks. Right now, if I need to test state, I am settings a prop as the initial value of a state, because it's clear to me where I can modify the props in the tests, but not clear how to modify the state.

**Comment by iam4x** [comment]
@djbobbydrake When testing components you should not change state programatically but fire an action that would do it and test if the UI changed the correct way!

And setting state from props in a component, like this:

```javascript
constructor(props, context) {
  super(props, context);

  this.state = { active: this.props.active }
}
```

Is a design error, you should pass an handler that will modify the props in the higher component.

This will make your components more simple and easier to test, you should read (if not already https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.uda8993qe

Hope it helps!

**Comment by djbobbydrake** [comment]
Thanks for the guidance. Was wondering if it was better design pattern to tie a component's state to external props, and seems like that should be the case. Will go ahead and do that. Thanks for taking the time to answer.

**Comment by iam4x** [comment]
No problem, don't hesitate to ask anything on the repo or on reactiflux discord!
