### ISSUE TITLE
Reloading Weirdness

### ISSUE THREAD

**Issue by willcodeforfoo** [iam4x/isomorphic-flux-boilerplate#14]
I'm working on bringing an app up to date with the latest webpack changes and noticed some weird behavior with regards to reloading.

Since webpack is now loading images, I was replacing some `<img />` tags in JSX so webpack could find them (e.g., `<img src={require('../images/foo.jpg')} />`). What's odd is hot reloading worked fine, but when hard-refreshing the page from the server I experienced an error.

Here is a little video I made while making the changes: http://assets.kevinmarsh.com.s3.amazonaws.com/20150414-Reloading-Weirdness.mp4

You can see hot reloading working well, then hard refreshing a the page with an error (not having the previous change), then reloading the server which results in a 500 error.

I tried this with the latest version of isomorphic-flux-boilerplate and it exhibits the same behavior. Hot reloading works fine, but refreshing the browser shows the previous version without the change.

**Comment by iam4x** [comment]
I think I have fixed this here: https://github.com/iam4x/isomorphic-flux-boilerplate/commit/bcffa10f5cfaf7705de148a0694e8a39d2f38af1#diff-2512af96bbb6d6a80f50954b526aad34R38

**Comment by willcodeforfoo** [comment]
That works! Thanks!

No `img` tags seems like a fairly large caveat. Is that a limitation of webpack?

**Comment by iam4x** [comment]
Should be fixed with #15 since it's merged :+1:

About using `<img src='xxx'>` I might find something, I'll open another issue.

**Comment by iam4x** [comment]
@willcodeforfoo Can you test with #30   ?
