### ISSUE TITLE
Server-side promise resolution and speed

### ISSUE THREAD

**Issue by djbobbydrake** [iam4x/isomorphic-flux-boilerplate#140]
I am running into an issue where promise resolution using alt-resolver on the server side results in very long render times.  Here is my request wrapped in alt-resolver:

```
    flux.resolve(async (done) => {
      try {
        const data = await axios(options);
        userActions.getAccountSuccess(data.data);
        flux.getActions('requests').success();
      }
      catch (e) {
        flux.getActions('requests').fail();
        debug('dev', 'koa')(`Error with getUser request: ${e.message}`);
      }
      return done();
    });
```

And here's what I'm seeing from Koa output:
```
 dev first render +3ms
  dev update page title to 'My Profile' +8ms
  dev second render +6s
  dev update page title to 'My Profile' +7ms
  dev return html content +8ms
```
As you can see, that second render takes upwards of 6 seconds. If I don't make the request server-side (via componentWillMount), then the page loads very quickly. Any thoughts on why I would be running into this issue?

**Comment by iam4x** [comment]
@djbobbydrake Seems like the request itself is long to resolve, it's an issue with your API.

**Comment by djbobbydrake** [comment]
I'll take more of a look, but the thing is, when the request to the same endpoint is made on the client-side, works pretty fast.  The endpoint is external to the app.  Does that matter?

**Comment by iam4x** [comment]
@djbobbydrake Maybe the connection between the rendering server and the API is bad, try to `$ traceroute { api_url }` on your rendering server to see what's happening.

We have multiple app in production using an external API without problems.
