### ISSUE TITLE
server redirect within action

### ISSUE THREAD

**Issue by stephenmuss** [iam4x/isomorphic-flux-boilerplate#141]
Hi,

I'm helping out on a project from more of a server-side perspective so I'm not really across all of the react stuff. Hopefully this isn't a stupid question.

In the project there is an action called `fetchByKey` which is used to fetch data asynchronously on the server sider. In some cases it may be necessary to do a server side redirect when certain conditions are met.

My main question is how can I achieve a server-side redirect from within the action? Is it possible or do I need to take another approach.

Thanks in advance

**Comment by iam4x** [comment]
@stephenmuss What's your solution? I was going to write you that you need to do it into a `onEnter` route hook from `react-router`.

**Comment by stephenmuss** [comment]
I just ended up creating my own router in koa to bypass react completely.

**Comment by iam4x** [comment]
Alright :)
