### ISSUE TITLE
When HOST = LOCAL_IP causes errors in Chrome

### ISSUE THREAD

**Issue by jaredkotoff** [iam4x/isomorphic-flux-boilerplate#144]
In `dev.config.js` HOST is being set to LOCAL_IP, which is my internal IP address. 
In Chrome console this generates an error every few seconds: 
`GET http://192.168.1.5:3001/__webpack_hmr net::ERR_CONNECTION_REFUSED`   `192.168.1.5:3001/__webpack_hmr:1`
Right now I am manually setting `const HOST = 'localhost';`  
Not sure if this is intended effect and something is going wrong for me or if its a Windows (10) problem.

**Comment by iam4x** [comment]
@jaredkotoff It's the intended effect to debug from other devices than your computer, like a mobile :+1: 

But it's weird that chrome can't connect on windows. What is your windows version? I'll set up a VM to test.

**Comment by jaredkotoff** [comment]
@iam4x Windows 10

**Comment by jaredkotoff** [comment]
Closing this.
Finally got around to testing on a different computer. This seems to be a isolated issue.  
Although, BrowserSync isn't working on THAT computer but probably unrelated to this repo.

**Comment by jaredkotoff** [comment]
Figured out that I had to change this line in start-koa.js from: 
```JSX
proxy: `0.0.0.0:${ parseInt(process.env.PORT, 10) || 3000 }`
```
To:
```JSX
proxy: `localhost:${ parseInt(process.env.PORT, 10) || 3000 }`
```
