### ISSUE TITLE
Proxy calls to remote REST endpoints

### ISSUE THREAD

**Issue by lovegroveandy** [iam4x/isomorphic-flux-boilerplate#145]
Is there any way to proxy requests made to external REST API's? What I mean by this is if I have a REST endpoint at https://api.me.com I would want to make a request to that endpoint without the full URL appearing in the network tab of developer tools. 

What I would like to achieve is a route on KOA such as /users that then proxies the call to https://api.me.com so the network tab only shows /users so the full URL is not visible on the client

Any help appreciated

**Comment by iam4x** [comment]
@lovegroveandy You can setup a proxy your external API on the koa server from the boilerplate. These modules can be useful:

* https://github.com/popomore/koa-proxy
* https://github.com/KualiCo/koa-pixie-proxy
* https://github.com/ming-codes/koa-http-proxy
* https://github.com/bornkiller/koa-proxy2

(I haven't looked into each of them)

**Comment by jaredkotoff** [comment]
Just tried koa-proxy and it seems to work great. Really easy straight forward install. Just modify your dev-server.js and koa.js files.

**Comment by lovegroveandy** [comment]
Thanks for the help, I managed to get this working with koa-proxy

**Comment by iam4x** [comment]
:+1:
