### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by lovegroveandy** [iam4x/isomorphic-flux-boilerplate#152]
Hi any idea how to approach getting this to work in IE 11, your demo site doesn't render at all?

**Comment by iam4x** [comment]
<img width="1052" alt="screen shot 2015-11-20 at 00 21 14" src="https://cloud.githubusercontent.com/assets/893837/11287561/d88fc9f4-8f1c-11e5-9c01-532c17244558.png">

This is on IE11, it should work for IE10 and IE9. There's issues with IE8 and babel class that I couldn't resolve yet.

**Comment by lovegroveandy** [comment]
Apologies, it would appear the test PC we have needs some coffee. Thanks for the speedy response.
