### ISSUE TITLE
How to avoid FOUC (Flash of unstyled content)

### ISSUE THREAD

**Issue by johnwp** [iam4x/isomorphic-flux-boilerplate#155]
I'm wondering if you have any ideas on how to avoid the FOUC (Flash of unstyled content) when running the dev server.  I'm having trouble getting an accurate DOM representation in componentDidMount():

```
componentDidMount() {
    
    setTimeout(() => {
        console.log(this.refs.handle.offsetWidth) // Logs correct value 
    }, 1000);

    console.log(this.refs.handle.offsetWidth); // Logs incorrect value 
    
}
```

**Comment by iam4x** [comment]
@johnwp In dev this would be hard since style are loaded through javascript inline (for the hotreload). You can use the `ExtractTextWebpackPlugin` in dev too to have the CSS loaded with the page.

**Comment by johnwp** [comment]
This seems to happen even when in production mode.  Have you seen this behavior before?
