### ISSUE TITLE
404 page not returning 404 HTTP status

### ISSUE THREAD

**Issue by taitsmp** [iam4x/isomorphic-flux-boilerplate#156]
When I make a request to incorrect URLs I get a 404 page but an HTTP 200 status code.   

Ideally koa.js would detect the missing page and return a 404 HTTP status code.  Getting the status code right would be especially useful when you put a caching solution in front of node and serve /assets requests via the cache. 404 responses from node would not be cached.

**Comment by iam4x** [comment]
You are right this is a bug.
