### ISSUE TITLE
Suggestions on zero downtime deployment.

### ISSUE THREAD

**Issue by djbobbydrake** [iam4x/isomorphic-flux-boilerplate#158]
Hey man, this boilerplate has been a life-saver. Thank you sooo much. 

I was interested in knowing your thoughts on how I could achieve zero downtime deployment with this repo.  I've got PM2 running in clustered mode, which seems to work fine.  But when I deploy and run `npm run build`, oftentimes the css files go missing and it looks like the site is down when it really isn't.  Any thoughts on how to remedy this?

**Comment by iam4x** [comment]
@djbobbydrake You can use capistrano or shipitjs to have multiple versions of your application on the server, and when new version is uploaded you can run `pm2 startOrGracefulRestart /full/path/to/processes.json` it will reload the application with 0 downtime.

At work we use http://deploybot.com/ which is basically capistrano/shipitjs but with a server and UI. You have to use Atomic SFTP and have theses commands:

After new verison is uploaded:
```
npm i --no-spin
NODE_ENV=production npm run build
```

After new version becomes active:
```
cd ~/
NODE_ENV=production pm2 startOrGracefulReload ~/current/processes.json
```

(Start pm2 in your home directory first, and do the reload into your home directory because there's an issue with pm2 and symlinked directory see https://github.com/Unitech/pm2/issues/1623)

Hope it helps!

**Comment by dmitry** [comment]
@djbobbydrake are you using an outdated boilerplate or with the very fresh changes? If it's an outdated, you have to remove cleaner that runs on each build.

**Comment by djbobbydrake** [comment]
Thanks @iam4x. Will look into that. @dmitry Boilerplate version is about 2-3 months old but with some manual updates from commit history. Don't see cleaner anywhere in the boilerplate.

I have an additional question. Is there a way to force the browser to reload when you deploy? Otherwise, the user won't see the latest code changes till after they reload their browser, but there's no guarantee when that will happen.

**Comment by dmitry** [comment]
I guess the best solution to notify browser about the new deployment would be constant check of the remote `webpack-stats.json` with local one (already loaded). If it changed, then you can show notification for the user, so they can refresh their session when they want it to.
It's already loaded on client side through: https://github.com/iam4x/isomorphic-flux-boilerplate/blob/3e57c59c275259383c8f918a9905f11319bb3d0e/app/utils/image-resolver.js#L19

**Comment by djbobbydrake** [comment]
Going to close this out. Thanks for the responses. Will need to investigate on my end.

**Comment by cridenour** [comment]
@djbobbydrake Just to clarify, the cleaner that @dmitry mentioned could also be in your package.json in the build command itself (removing files inside dist/). That is the only reason pm2 in cluster should ever have a problem. 

We run in cluster and have AFAIK absolute zero downtime on a new build.

**Comment by djbobbydrake** [comment]
@cridenour @dmitry - So am still running into this issue with missing js file. I removed the code that removes the dist file, but still seems like Cloudfront CDN is serving a cached 404 from the missing js file. What's the possibility that someone hits the homepage and the js file hasn't been built yet by webpack?

**Comment by cridenour** [comment]
@djbobbydrake Depends on how your build process works! We are hosting the static files on our app server at our scale without issue, so when I run `npm run build && pm2 reload all` I know that the files will be there.

The beauty of not removing the current files is that you can build your files, wait for them to propagate across your CDN and only then restart your app.

**Comment by djbobbydrake** [comment]
I've got a shell script that runs:
```npm run build
pm2 reload app```

The missing js file is the last one that was generated in the /dist folder.

**Comment by cridenour** [comment]
Yea sounds like you're just too quick for Cloudfront to see the new file in S3 and get it out to all your servers. 

You'll can always do the very fancy:
```bash
npm run build
sleep 5
pm2 reload app
```

**Comment by djbobbydrake** [comment]
Thanks for the suggestion. I am going to try that and see how things go.
