### ISSUE TITLE
Unhandled promise rejection Error...

### ISSUE THREAD

**Issue by SPAHI4** [iam4x/isomorphic-flux-boilerplate#159]
I have ItemsStore connected with Header and Items components. 
When url is /items and i trying to change something in ItemsStore all works fine. But if i do changes when im on the main page / i got this error
```
Unhandled promise rejection Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.(…)
```

**Comment by iam4x** [comment]
Hello @SPAHI4,

This means you may have two actions firing a state change at the same time, or a page transition when a state change occur. You can use `flux.getActions('xxxx').actionName.defer();` to defer actions when you have this kind of concurrency.

You should find more information about that into reactiflux discord altjs channel.

**Comment by SPAHI4** [comment]
Thanks 
It was problem with setting title
