### ISSUE TITLE
Dependency problem (history)

### ISSUE THREAD

**Issue by Bogdaan** [iam4x/isomorphic-flux-boilerplate#163]
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package history@1.15.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.2 wants history@1.13.x
npm ERR! peerinvalid Peer scroll-behavior@0.3.0 wants history@^1.12.1

( For my case - i remove scroll-behavior )

**Comment by Antonhansel** [comment]
Same issue here on a fresh install, using nodejs@4.2.1.

**Comment by dmitry** [comment]
Does the `npm purge` and then install helps?

**Comment by AllenFang** [comment]
+1

**Comment by iam4x** [comment]
Fixed with #165 :+1:
