### ISSUE TITLE
css is not loading

### ISSUE THREAD

**Issue by bokzor** [iam4x/isomorphic-flux-boilerplate#166]
In the last version, css is not loaded anymore

**Comment by iam4x** [comment]
@bokzor I can't reproduce, do you have more informations? Is it a fresh clone? What is your OS, node version and npm version?

**Comment by bokzor** [comment]
npm 3.3 & node 5.1.
And yes It was a fresh clone. But I think it may because of npm-check package...

**Comment by iam4x** [comment]
It's supported by node 5.1 which has breaking changes, use an LTS version. I'm not planning to update to 5.1 soon.

I'm open to PR for 5.1 and 4.2.x support together :+1:
