### ISSUE TITLE
How to use Immutable JS with this boilerplate

### ISSUE THREAD

**Issue by djbobbydrake** [iam4x/isomorphic-flux-boilerplate#171]
I've been trying to figure out how to implement Immutable-JS in the stores in this template but can't seem to get it to fully work.  Any thoughts on this?  I've tried some suggestions from https://github.com/goatslacker/alt/blob/master/docs/utils/immutable.md, but no luck.

**Comment by djbobbydrake** [comment]
Got this to work using the ES7 decorator.  The one thing I wasn't doing was setting the entire state object to an Immutable object.  My store looks something like:

```javascript
import moment from 'moment-timezone';
import Immutable from 'immutable';
import immutable from 'alt/utils/ImmutableUtil';

@immutable
class FiltersStore {
  constructor() {
    this.bindActions(this.alt.getActions('filters'));

    const filtersStruct = {
      momentStart: undefined,
      momentEnd: undefined,
      activeDay: undefined
    };
  
    // Needed to do below.
    this.state = Immutable.Map({
      provider: Immutable.Record(filtersStruct),
      activities: Immutable.Record(filtersStruct)
    });
  }

  onInitDateTime() {
    const defaults = {
      provider: {
        momentStart: moment().tz(process.env.TIMEZONE),
        momentEnd: moment().hours(23).minute(0).seconds(0).tz(process.env.TIMEZONE),
        activeDay: moment().tz(process.env.TIMEZONE)
      }
    };
    // this.state here is an immutable map, so we can call the immutable methods on it
    this.setState(this.state.merge(defaults));
  }
}
```

Hope this also helps other folks implement.

**Comment by djbobbydrake** [comment]
Solved this. So closing.

**Comment by utkuturunc** [comment]
@djbobbydrake How do you connect to components? The same way?

**Comment by djbobbydrake** [comment]
@utkuturunc - You can connect to the immutable store the same way you would connect to a non-immutable store. The only different is that with an immutable store, an immutable object is returned. Some things to keep in mind.

1. Wherever you want to work with whatever data is in your immutable store - ```const filterStore = flux.getStore('filters').getState()``` - ```filterStore``` is an immutable object
2. If this immutable store is passed into your component from a parent component, remember that the PropType is an immutable object

**Comment by utkuturunc** [comment]
I was thinking someting like:

```
@connect(({ images }) => ({ count: images.get('count') }))
```

or even 

```
@connect(({ images }) => ({ imageStore: images.toJS() }))
```

so that getting values from props is easier.

**Comment by djbobbydrake** [comment]
Yeah, you can take that approach. I've found that when you have a lot of components, it's hard to keep track of things if you're connecting one store to one component. We've taken the approach of lots of dumb components, and a few controller components. Those controller components hook up to stores, and pass props down to the child components. The child components are, for the most part, unaware of stores. They're just passed props.

**Comment by utkuturunc** [comment]
@djbobbydrake That is the exact approach I am trying to take with this exception.

The first time componentWillMount runs, I have undefined for _root of the immutableMap (and most of other fields). Possibly, the store gets listened afterwards.

**Comment by djbobbydrake** [comment]
@utkuturunc We add our store listeners in componentDidMount. I think that is the standard practice. In our implementation, ajax requests are made that populate our stores. The recommendation from Facebook is to trigger those ajax requests in componentDidMount. That means if we request information from the store in componentWillMount, that store will be empty (on the initial page load). There is a chance, if you have a single page application and the page request isn't your very first page request, that you will already have data in your store at componentWillMount(), but it wouldn't be available on the first page load because we have to wait for the ajax request to return data that then is used to populate the store.  Can you try adding your store listener in componentDidMount() instead?
