### ISSUE TITLE
Proper way hand data to actions

### ISSUE THREAD

**Issue by jaredkotoff** [iam4x/isomorphic-flux-boilerplate#174]
Before I was doing something like this
```JavaScript
fetchUser(userID) {
    // We only allow logged in users to fetchUser
    const token = this.alt.getStore('session').getState().session.token;
...
```
Now I'm thinking it has to be done like this, passing the token in the component
```JavaScript
fetchUser(userID, token) {
```
Is this what is recommended or is there a cleaner way to get store data into an action?

**Comment by AllenFang** [comment]
I thinks get data from store in an action is a not good idea In flux pattern, The flow should be getting <code>token</code> and <code>userID</code> in component and passing to action. if too many params, you can wrap it as an object.

**Comment by jaredkotoff** [comment]
@AllenFang that's kind of what I was thinking too. Thanks for the reassurance.
