### ISSUE TITLE
UglifyJS ES6 Problem

### ISSUE THREAD

**Issue by utkuturunc** [iam4x/isomorphic-flux-boilerplate#183]
I am using koa-passport@2 (koa2 version of the middleware). Version 2 of this middleware is written in ES6 which causes the following error with uglifyjs:

```
ERROR in app-fdcd867d1056a514a3b0.js from UglifyJs
Unexpected token: operator (>) [./~/koa-passport/lib/framework/koa.js:47,0]
```

The line from the library is the first one in which an arrow function is used. These types of modules should be converted to ES5 before uglifying.

**Comment by utkuturunc** [comment]
To anyone having the same problem, you can add the following line to your webpack base config.

```
      { test: JS_REGEX, include: /node_modules\/koa-passport/, loader: 'babel' }
```

below the line

```
      { test: JS_REGEX, exclude: /node_modules/, loader: 'babel' },
```

**Comment by iam4x** [comment]
@utkuturunc I don't understand why you need to bundle `koa-passport` into your dist file. This should only be on server side?

**Comment by utkuturunc** [comment]
Anyone having the same problem check #176

**Comment by SPAHI4** [comment]
Thanks helps me with same problem with ```joi```
