### ISSUE TITLE
The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by AllenFang** [iam4x/isomorphic-flux-boilerplate#192]
there's some error when run <code>npm install</code>
```
npm ERR! peerinvalid The package history@1.13.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.3 wants history@^1.17.0
npm ERR! peerinvalid Peer scroll-behavior@0.3.0 wants history@^1.12.1
```

Any idea to solve it?
Thanks

**Comment by donaldparker** [comment]
I upgraded NPM and it worked.

**Comment by AllenFang** [comment]
@donaldparker, but my npm is <code>v2.14.4</code>

**Comment by AllenFang** [comment]
@donaldparker, yap, npm3 will no longer install <code>peerDependencies</code>. We can add a documents to remind user upgrade their npm. But I thinks this solution is just a workaround, if <code>scroll-behavior</code> could upgrade the version of <code>history</code> is a best condition

**Comment by iam4x** [comment]
Created an issue on `scroll-behaviour` waiting for more informations :+1:

**Comment by AllenFang** [comment]
Thanks @iam4x, I check https://github.com/rackt/scroll-behavior/issues/23 and https://github.com/rackt/scroll-behavior/issues/26. But I still dont know how to solve this issue ;(

**Comment by iam4x** [comment]
I've updated to history@1.17 works :+1:
