### ISSUE TITLE
Support for generators has been removed from KOA.

### ISSUE THREAD

**Issue by donaldparker** [iam4x/isomorphic-flux-boilerplate#194]
Getting 
TypeError: Support for generators has been removed. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa#example-with-old-signature...

Changing app.use(helmet()); to  app.use(convert(helmet())); appears to resolve the issue.

**Comment by jaredkotoff** [comment]
Or update helmet to ^2.0.0-alpha.1 is what I did.

**Comment by donaldparker** [comment]
@jaredkotoff kind of off topic, but were you able to get the hot reloader to work?

**Comment by jaredkotoff** [comment]
@donaldparker Yea hot reloading seems to be working for me. 
Maybe give be a specific scenario you want me to try out.

**Comment by donaldparker** [comment]
Fresh clone of the repo, with a clean NPM cache. It works for me with a clone from about a month ago, newer clones do not appear to function correctly.
