### ISSUE TITLE
Hot middleware not reloading

### ISSUE THREAD

**Issue by donaldparker** [iam4x/isomorphic-flux-boilerplate#197]
Currently updating a module requires a stop and start of the server for the changes to be reflected in the browser.

**Comment by iam4x** [comment]
What is your nodejs, npm and os version?

**Comment by donaldparker** [comment]
npm 3.5.2
node 4.2.2
OSX 10.10.5

**Comment by iam4x** [comment]
I can't reproduce, what type of code are you modifying? Adding text into a `render()` works for me, and changing handler as well.

**Comment by donaldparker** [comment]
I removed nvm, all versions of node & io.js, and clean install of all packages and appears to be working again, sorry for the miscommunication.
