### ISSUE TITLE
Can't run on windows 8.1

### ISSUE THREAD

**Issue by doodledood** [iam4x/isomorphic-flux-boilerplate#21]
When I try to run 'npm run dev' I get the following error:
'DEBUG' is not recognized as an internal or external command

**Comment by iam4x** [comment]
It seems to be windows specific https://github.com/visionmedia/debug#windows-note

For now as workaround you can change your `package.json` at `script` key, the `dev` one, and remove `DEBUG=....` at the beginning.

I'll will install a VM tomorrow, can you link me some tools how to have a CLI / NPM and git on windows to debug this issue?

Thank's!

**Comment by doodledood** [comment]
Sure, first of all download and install: 
* [http://git-scm.com/download/win](git)
* [https://iojs.org/dist/latest/iojs-v1.7.1-x64.msi](iojs)

Npm should come with the latest release of node. 
From there open "cmd.exe" and proceed normally.

Thanks for your efforts.

**Comment by doodledood** [comment]
By the way,
'npm install' also fails when trying to build webpack-dev-server.
There is a some issue with it on windows. 
[https://github.com/Automattic/socket.io/issues/2057](This solves it)

But I still can't get rid of 'Error: `libsass` bindings not found. Try reinstalling `node-sass`?' even tough I followed the advice outlined in README.md

**Comment by iam4x** [comment]
@doodledood I've just installed everything, no problems with `node-sass`. Try to `npm cache clear` and `npm install node-sass`

**Comment by iam4x** [comment]
For `node-sass` I had to do:

* Install python27, add `python` to your env path (http://stackoverflow.com/a/6318188)
* Install VS Express 2013 for building with `node-gyp`
* `$ npm cache clear`
* `$ npm install node-sass`

And then `$ npm run build` worked.

**Comment by doodledood** [comment]
Did you manage to run everything on windows?

**Comment by iam4x** [comment]
There's an issue with `koa-proxy` for loading assets I need to check that.

But `node server/index.js` after `npm run build` is working correctly

**Comment by iam4x** [comment]
Everything is good after removing a rule of `jscs` about the end line. 

I will change validation of end line with https://help.github.com/articles/dealing-with-line-endings/#re-normalizing-a-repository

![screen shot 2015-04-17 at 18 55 11 2](https://cloud.githubusercontent.com/assets/893837/7206642/acd2b7b0-e533-11e4-9cdf-c1166bc26ae1.png)

**Comment by iam4x** [comment]
Just noticed it's windows 7, I don't know if it changes a lot for iojs to run on windows 8

**Comment by doodledood** [comment]
Okay, I checked out the branch and weird stuff are happening:
* With iojs (v0.17.1) I still get '`libsass` bindings not found. Try reinstalling `node-sass`?', no matter what I try.
* With node (v0.12.2) I get 'SyntaxError: Unexpected token ILLEGAL' - which I suspect has something to do with jscs and babel...

**Comment by iam4x** [comment]
Can you `npm install node-sass`? Without errors?

**Comment by doodledood** [comment]
Yes I can.
But the problem is that 'npm run build' returns some errors of 'Module didn't self register' for node-sass anyways and babel-core.
I have tried to clone the repo to another folder, removing node and iojs completely and reinstalling iojs, removing npm cache and installing updated dependecies but non seem to work ><

**Comment by iam4x** [comment]
Okey let me download windows 8

![image](https://cloud.githubusercontent.com/assets/893837/7209352/533b06f2-e548-11e4-86ee-f7b67b5542ed.png)

**Comment by doodledood** [comment]
@iam4x let me know if it works as if it does, it might be that my system is polluted somehow...

**Comment by iam4x** [comment]
No luck with windows 8.1 :( Same issue... You should report issue into babel and node-sass.

**Comment by doodledood** [comment]
sass/node-sass#870
