### ISSUE TITLE
Can't load fonts

### ISSUE THREAD

**Issue by noradaiko** [iam4x/isomorphic-flux-boilerplate#210]
I'm using it with semantic-ui but it failed to load fonts on dev server.
The browser always attempts to load `http://localhost:3002/` as the font url and outputs following warnings:

```
Failed to decode downloaded font: http://localhost:3002/
OTS parsing error: invalid version tag
```

I found it can be solved by adding `http:` to `PUBLIC_PATH` in `dev.config.js` as follow:

```
const PUBLIC_PATH = `http://${HOST}:${PORT}/assets/`;
```

**Comment by iam4x** [comment]
@noradaiko Yes, there's a lot of problems with source of assets in dev-mode. Your fix works, but if you go on another device with your local ip it wont work.

The best solution I think is to use `url-loader` for dev-mode instead of `file-loader` in webpack.

**Comment by jaredkotoff** [comment]
Is this the same reason that `background-image: url()` css is broken too?

**Comment by iam4x** [comment]
@jaredkotoff Exactly, I'm going to fix that :+1:

**Comment by noradaiko** [comment]
:+1: great

**Comment by SPAHI4** [comment]
:+1: thanks god now i can use sourcemap
