### ISSUE TITLE
Webpack dev server fully reloads app after updating code

### ISSUE THREAD

**Issue by jchapple** [iam4x/isomorphic-flux-boilerplate#213]
Hello,

I'm not too sure what's causing this, but recently I've noticed that when I'm editing components, stores, actions, etc., after the HMR update happens (successfully), the page then does a hard reload. 

Any ideas what's going on here?

Cheers

**Comment by iam4x** [comment]
Hey @jchapple 

Can you debug https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/webpack/utils/start-koa.js#L50-L55 and see which files triggers the full reload?

**Comment by jchapple** [comment]
Hey @iam4x! Sorry for the delayed reply and thanks a lot for your response.

So this was actually happening because I had modified `webpack/utils/write-stats` to write a file at `webpack-stats-full.json` that contains the full stats, as well as the existing `webpack-stats.json`, so that I could analyse the bundle output with the [Webpack analyser](https://webpack.github.io/analyse/). This is what was triggering the unwanted hard reload.

Thanks for pointing out those lines! Hadn't noticed this part before. :)

All the best.
