### ISSUE TITLE
Better way to handle nested localized messages?

### ISSUE THREAD

**Issue by jaredkotoff** [iam4x/isomorphic-flux-boilerplate#218]
I was trying to do something like this: https://github.com/yahoo/react-intl/issues/137#issuecomment-120416578 
But, with the current impllimintation of i18n I ended up with this code: 
```JSX
<FormattedMessage
  message={ i18n('profile.joined', { date: '{ date }' }) }
  date={ 
    <FormattedDate
      value={ joinDate }
      month='long'
      year='numeric'/>
  } />
```  
It's pertty hacky because i had to "print" out `{ date }` from i18n so that `<FormatedMessage>` will catch it and then render `<FormattedDate>`  
I want to do this because it really clears up and simplifies the localization source files allowing full sentances rather than broken up words. Any suggestions?

**Comment by iam4x** [comment]
What you can do is:

into your locale store:
```
this.formats = {
  long: 'mm dd yyyy...'
};
```
i18n('profile.joined', { joinedDate });
```

and your message will look like:

```
profile: { joined: 'User joined on { joinedDate, date, long }' }
```
