### ISSUE TITLE
SourceMap on browser not working

### ISSUE THREAD

**Issue by noradaiko** [iam4x/isomorphic-flux-boilerplate#223]
Logging via `debug` module on browser causes source map not working.
Setting Chrome's framework blackboxing also does not work (because of webpack URL?).
How to manage it?

![screen shot 2016-01-29 at 20 43 55](https://cloud.githubusercontent.com/assets/1332805/12674812/14aea21e-c6c9-11e5-823c-f36dce95d53e.png)

**Comment by jaredkotoff** [comment]
:+1:

**Comment by iam4x** [comment]
I don't understand your issue, you have the file name with the line correctly set in your logs?

**Comment by noradaiko** [comment]
Sorry for my poor expression.

When I use `console.log` the chrome dev tools add a link to the line of code where that console.log statement was executed.
But with `debug` module, the dev tool always links every logs to `debug/browser.js:112`.
This issue is discussed at https://github.com/visionmedia/debug/issues/229.
A simple solution is usually to use [Blackboxing](https://developer.chrome.com/devtools/docs/blackboxing) that lets blackbox a source file so the debugger will not jump into that file when stepping through code you're debugging.
The problem was the Blackboxing is somehow not working in this boilerplate in my case.

My workaround is to set `devtool` to `eval-source-map` in `base.config.js` and to use the latest Chromium instead of Google Chrome because the Blackboxing is possibly not working for inline scripts such as created with Browserify (See https://github.com/visionmedia/debug/issues/198#issuecomment-174852594).
With this configuration dev tool links expected lines like following.

Before:
![screen shot 2016-04-07 at 18 57 14](https://cloud.githubusercontent.com/assets/1332805/14347536/98158eba-fcf2-11e5-89df-395f11c118ff.png)

After:
![screen shot 2016-04-07 at 18 47 38](https://cloud.githubusercontent.com/assets/1332805/14347285/3c7f6504-fcf1-11e5-8629-4cdbee5ce2d4.png)

it may not be this project's issue though I'd just report.
regards.
