### ISSUE TITLE
Use Inline CSS

### ISSUE THREAD

**Issue by doodledood** [iam4x/isomorphic-flux-boilerplate#25]
Following the advice from [React CSS In JS](https://speakerdeck.com/vjeux/react-css-in-js),
advice from the official documentation of react it self, and my own experiments, I think it would be a nice replacement to sass in the boilerplate.

What do you think?

Libraries such as [react-inline-css](https://github.com/RickWong/react-inline-css) or [radium](http://projects.formidablelabs.com/radium) can be helpful if it is decided to adopt this idea.

**Comment by dmitry** [comment]
Nice idea, but still the best practice approach isn't deliveried. You can join this https://github.com/VirtualCSS/planning/issues/1 discussion to talk more about visualization layer inside react.

**Comment by iam4x** [comment]
I'm not much into inline-css yet and I prefere to keep an example with css / sass.

But for for example you can make PR with a component with inline style with it too.

**Comment by dmitry** [comment]
With this https://github.com/martinandert/react-inline module you can write styles in components, but in the production these styles can be bundled into a separate stylesheet .css file. I believe it's the full featured solution at the moment.

**Comment by iam4x** [comment]
Do you want to add an example on how to user inline styles on one of the components @doodledood ?

**Comment by doodledood** [comment]
Maybe we should wait with this as it seems like [react-style](https://github.com/js-next/react-style) might to be merged into react itself.

By the way,
[This](http://www.slideshare.net/bensmithett/presentation-38906546) is another good presentation in favor of css in js.

**Comment by iam4x** [comment]
I like the presentation, I won't use it yet for my productions app but it's a good direction!

Let's wait for the merge if it happens, is there an open PR/Issue on React repo for it?

**Comment by doodledood** [comment]
There is an issue preventing the merge apparently.

https://github.com/js-next/react-style#why-isnt-this-included-inside-reactjs-yet

**Comment by totty90** [comment]
> React Style does not support CSS selectors, pseudo-classes and CSS animation

[smart-css](https://github.com/hackhat/smart-css) has all except CSS animations, which are coming soon.
