### ISSUE TITLE
Alt-resolver should clean up promises earlier

### ISSUE THREAD

**Issue by MrOrz** [iam4x/isomorphic-flux-boilerplate#28]
Currently, alt-resolver cleans up `toResolve` after all promises are resolved.

https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/app/utils/alt-resolver.js#L57

However, if there is another request coming in when the previous request's promises are not fully resolved yet, the second request would have to wait for the previous request's promises as well, since the previous request's promises are still inside `toResolve`. Although it does not affect the data integrity (since data in different requests are still kept inside different contexts), it may hurt the throughput of the server-side app.

**Comment by iam4x** [comment]
I see two solutions:

Clean promises asap or use alt-resolver into a actions/store since we use instances of alt now, maybe more a "flux" way of doing things.

See also: https://github.com/goatslacker/alt/issues/122 alt-resolver might change a lot when this will be decided.

**Comment by MrOrz** [comment]
In an example app I built for a talk, I [just clean up promises ASAP](https://github.com/MrOrz/flutefish/blob/master/server/server.js#L101).

Implementing alt-resolver as a flux action + store sounds good, since we can make good use of the alt instances, which are already separated per request. However, if alt-resolver were broken down into an action and a store, I cannot think of a meaningful state to store inside the store. Maybe just a boolean value that indicates all stuff has been resolved and it's ok to render? Secondly, in this way alt-resolver would dispatch an event when all promises are resolved; Promises handled by alt-resolver also dispatch to their own store. If any of the promise resolves synchronously, we may dispatch in the middle of a dispatch, which causes error.

It may also work if we implement alt-resolver as a sole flux action that keeps track of promises in its own private variable. Statements like `content = yield alt.getActions('altResolver').render(...)` looks a bit strange to me though, becuase I haven't seen an action that would return a promise that resolves to meaningful data, instead of populating those data to stores.

**Comment by doodledood** [comment]
Why not just export a class that owns the promises and then instansiate it once on every request and once on the browser? 
Shared state is always a bad idea

**Comment by iam4x** [comment]
@MrOrz Thank's for feedback it makes sense, let's clean promises before :+1:

@doodledood Any code example? I can't really see what you mean.

**Comment by iam4x** [comment]
@MrOrz https://github.com/MrOrz/flutefish/blob/master/server/server.js#L87

This will call the resolver to collect the promises again, you need to clean right after it also. Or there will still be promises saved :)

**Comment by doodledood** [comment]
I might have some time in a few days and I will try to make an example

**Comment by MrOrz** [comment]
@iam4x Thanks for the correction! I didn't even notice that. Maybe instead of clearing collected promises ASAP, we should just clear the promises just before each `React.renderToString`.

Looking forward to @doodledood 's example!

**Comment by iam4x** [comment]
I find it more understandable like this:

- Render
- Collect
- Clean
- Resolve
- Render
- Clean

Why would you clean promises before the render? It's assuming you already had a request :)

I close this issue, feel free to ping @doodledood when you have an example :)

**Comment by doodledood** [comment]
Just created an example - see pull request #32
