### ISSUE TITLE
browsersync polling is spamming my terminal output

### ISSUE THREAD

**Issue by joeframbach** [iam4x/isomorphic-flux-boilerplate#31]
When I run the dev server, my terminal is spammed with this:

    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193331-7236
    dev first render +23ms
    dev second render +8ms
    dev return html content +3ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193331-7236 200 33ms -
    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193366-7237
    dev first render +14ms
    dev second render +4ms
    dev return html content +9ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193366-7237 200 26ms -
    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193392-7238
    dev first render +25ms
    dev second render +5ms
    dev return html content +3ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193392-7238 200 34ms -
    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193267-7234
    dev first render +18ms
    dev second render +4ms
    dev return html content +3ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193267-7234 200 25ms -
    koa blocked for 42ms +1ms
    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193447-7240
    dev first render +16ms
    dev second render +3ms
    dev return html content +4ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193447-7240 200 25ms -
    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193471-7241
    dev first render +30ms
    dev second render +5ms
    dev return html content +4ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193471-7241 200 37ms -
    <-- GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193492-7242
    dev first render +15ms
    dev second render +4ms
    dev return html content +3ms
    --> GET /browser-sync/socket.io/?EIO=3&transport=polling&t=1429553193492-7242 200 22ms -

It just keeps coming. If something actually important happens, I wouldn't know.

How can I at least tame this polling to, say, once every 2000ms rather than repeatedly?

**Comment by iam4x** [comment]
browserSync use [debug](https://github.com/visionmedia/debug) for logging, check your env variable `DEBUG` and set it to `koa,dev` for the boilerplate.

It's now done programmatically for windows support (see: https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/server%2Fkoa.js#L47)

**Comment by iam4x** [comment]
Wait, I haven't looked right at the logs.

It seems like browserSync is polling the koa server directly, it shouldn't be this way.

What is your navigator and system?

**Comment by joeframbach** [comment]
OSX 10.10.2, iojs 1.7.1, chrome 41

**Comment by iam4x** [comment]
I can't reproduce it, is it happening with the master branch of the boilerplate? Or with a fork you did?

**Comment by joeframbach** [comment]
Interestingly, I can't reproduce this either. I did reboot my macbook. Very strange indeed. I'll mark as closed since I can't reproduce this.

**Comment by iam4x** [comment]
Cool :+1:

**Comment by jenyckee** [comment]
Same here

x.x.x.x:4000/socket.io/?EIO=3&transport=polling&t=1435582066694-6:1 GET http://x.x.x.x:4000/socket.io/?EIO=3&transport=polling&t=1435582066694-6 net::ERR_CONNECTION_TIMED_OUT

**Comment by miklax** [comment]
Flood happens because app port and sockets ports are same. Change io.connect('http://localhost:3050'); from 3000 for example
