### ISSUE TITLE
isCashed flag in server/router.jsx

### ISSUE THREAD

**Issue by sogko** [iam4x/isomorphic-flux-boilerplate#33]
Hi,
I'm trying to pour through the comprehensively-built boilerplate in order to understand it better.

I'm curious about [this line in the server routes regarding cashed (cache?)](https://github.com/iam4x/isomorphic-flux-boilerplate/blob/d590782bc2d625ca0aa6700a5732d72b6de6315f/server/router.jsx#L16)

I can't find any other references to the ```isCashed``` member, are there magic involved?

Thanks in advanced for your time!

**Comment by iam4x** [comment]
I should add a comment in the code, it comes from koa-cash (https://github.com/koajs/cash).

**Comment by sogko** [comment]
Ah alright now that makes sense lol

But I still couldn't find references to ```this.isCashed``` in koa-cash. 
But the documentation does hint at using ```yield* this.cashed()``` to check if the request has been served from cached.

Thanks for your time again  👍

**Comment by iam4x** [comment]
Nice find, I did this really fast for testing.

Do you mind doing me a PR? :+1:

**Comment by sogko** [comment]
Sure, not a problem. Created PR #34

Thanks again! 👍

**Comment by iam4x** [comment]
#34 merged
