### ISSUE TITLE
Server redirect not working

### ISSUE THREAD

**Issue by adamjv90** [iam4x/isomorphic-flux-boilerplate#39]
If i define a redirect route
```
<Route name='another' handler={} />
<Redirect from='/from' to='another' />
```
and the initial request is set to /from then page load just seems to hang. 

I did notice that there was a TODO note inside server/router.js
```
// TODO: Try to render the good page with re-creating a Router,
// and with modifying req with `redirect.to`
```
Inside that onAbort function you seem to be setting the status and redirecting with koa functions but `this` would reference the instance of the router.

I don't really care about rendering the initial page. Just wondering if you had any input on this or have already thought of a solution.

**Comment by iam4x** [comment]
Yes it was for the first version using express, let me check this :+1:

**Comment by iam4x** [comment]
Can you checkout `fix-redirect` branch and tell me if it's good for you?

**Comment by iam4x** [comment]
@adamjv90 I needed it, it's merged. Feel free to re-open if it's not working.

**Comment by adamjv90** [comment]
yes it is working after merging in your changes from the fix-redirect branch, great job!
