### ISSUE TITLE
Use Alt's IsomorphicRender

### ISSUE THREAD

**Issue by doodledood** [iam4x/isomorphic-flux-boilerplate#4]
Alt's IsomorphicRender (https://github.com/goatslacker/alt/blob/master/utils/IsomorphicRenderer.js) can be used in router.jsx
It might make things a little simpler.

**Comment by iam4x** [comment]
@doodledood I'll give it a shot :+1:

**Comment by iam4x** [comment]
I can't find it really useful for the client side, I will certainly write my own helper. Because of `AltResolver` for fetching stores before rendering.

I will maybe change for https://github.com/ericclemmons/react-resolver

**Comment by iam4x** [comment]
I changed the whole rendering process with the new `alt-resolver`
