### ISSUE TITLE
transform undefined 

### ISSUE THREAD

**Issue by adamjv90** [iam4x/isomorphic-flux-boilerplate#43]
came across this error when trying to boot up the boilerplate. 

```
ERROR in ./app/index.js

/Users/adam/Code/smp/vault/app/index.js
  0:0  error  transform is not defined

✖ 1 problem (1 error, 0 warnings)


ERROR in ./app/main.js

/Users/adam/Code/smp/vault/app/main.js
  0:0  error  transform is not defined
```

this error occurs for almost every js file. any ideas?

**Comment by wuichen** [comment]
having the same problem

**Comment by iam4x** [comment]
I have no clue, maybe something with babel transform?

Is this happening with a clean install?

**Comment by adamjv90** [comment]
I did try it with a clean install and the same error occurred. Tested with node v0.12.2 and iojs v1.8 , both of which produced this error. In order to be able to still work with the boilerplate I ended up commenting out 
```
new webpack.NoErrorsPlugin()
```
of the dev webpack config.

**Comment by iam4x** [comment]
Maybe more something with UglifyJS2: https://github.com/mishoo/UglifyJS2/issues/357 ?

**Comment by wuichen** [comment]
updating the repo solved the problem
