### ISSUE TITLE
Introduce service worker for static asset precaching

### ISSUE THREAD

**Issue by EugeneHlushko** [iam4x/isomorphic-flux-boilerplate#432]
Hi @iam4x, do you want Service Worker set-up in the boilerplate? I can add this weekend.

**Comment by iam4x** [comment]
Hey @EugeneHlushko,

I haven't used SW yet, I will be more than happy to see some real example. Are you going to use https://github.com/GoogleChrome/sw-precache ?

**Comment by EugeneHlushko** [comment]
Hi @iam4x , here is a good reference: https://addyosmani.com/blog/progressive-web-apps-with-react/

I am planning to use: sw-precache-webpack-plugin which is really powerful and nicely set-upped via webpack config, also i am going to modify production env server a little bit to have offline support for sw

**Comment by iam4x** [comment]
@EugeneHlushko Great idea 👍

**Comment by EugeneHlushko** [comment]
Cool, will try to add it over the weekend

**Comment by EugeneHlushko** [comment]
Just a look back at how quick open source might be if you have a full time job 🥇

**Comment by EugeneHlushko** [comment]
Added to master.
