### ISSUE TITLE
a second of css loading on start and refresh

### ISSUE THREAD

**Issue by wuichen** [iam4x/isomorphic-flux-boilerplate#44]
When i run the code on localhost, theres a second of flash showing contents without css rendered. After it, it looks fine. Is this normal? 

![screen shot 2015-05-05 at 11 01 16 am](https://cloud.githubusercontent.com/assets/6353587/7479605/a80e380c-f317-11e4-8972-6231eddf0c60.png)
![screen shot 2015-05-05 at 11 01 18 am](https://cloud.githubusercontent.com/assets/6353587/7479616/b62b887c-f317-11e4-91fb-2581e4abb131.png)

![screen shot 2015-05-05 at 10 59 59 am](https://cloud.githubusercontent.com/assets/6353587/7479624/c0757040-f317-11e4-9629-e8b13d83b785.png)

**Comment by adamjv90** [comment]
I noticed this only happens when running the dev server. After doing a build and running in production mode there is no more jump.

**Comment by wuichen** [comment]
@adamjv90 yea it does solve the problem with build

**Comment by iam4x** [comment]
Yes because on dev it's inline CSS computed by webpack. We need this to have hot reload on CSS.

When the app is builded, it will be served externally by the koa server ;)
