### ISSUE TITLE
Question: returning sitemap.xml

### ISSUE THREAD

**Issue by nodexchange** [iam4x/isomorphic-flux-boilerplate#454]
Hi team, 

First and foremost, a massive thank you for all of your hard work on this brilliant project. I've never seen a faster and more reliable framework for any of my previous projects. 

I've encountered a bit of an issue or question, as I am trying to submit a sitemap.xml document to the google search console. How would you advise to link the react-router with your universal render to only return a plain xml file? Would it require from me to update the webpack plugins and then include it into the static assets xml? 

Let me know your suggested way. 

many thanks, 
martin

**Comment by EugeneHlushko** [comment]
Hi @nodexchange,

Please take a look here: https://github.com/iam4x/isomorphic-flux-boilerplate/pull/436/files#diff-a0a939eb1d86793bd72eb3f026270f59R62

I am looking to add a static assets folder for files such as robots.txt, sitemap.xml, manifest.json etc.
You can meanwhile use the same technique in your project.

Hey @iam4x,
Maybe you want to add this static folder i have in PR to dev version also? I might submit a PR if you dont have time for SW.
