### ISSUE TITLE
Use the boilerplate in a 'hybrid' way (client side rendering only)

### ISSUE THREAD

**Issue by denisflorkin** [iam4x/isomorphic-flux-boilerplate#467]
Hello,

for a project, we decided to use react. I am pushing to use this boilerplate as I have worked with it already and really like it.
The thing is that I am not yet sure that we'll have a node server but I intend to push for that too, so waiting for a definitive answer on that I would like to let the door open to 'universal' rendering, but the dev has to start pretty soon.
So my question is : would there be any way to modify the build process or add an alternative one that would allow for client side rendering to work without the node server-side rendering.
Instead we would probably serve an 'app shel' from a php backend or similar and have react starts its work only once on the client and without the server-side-pre-rendered html.

**Comment by EugeneHlushko** [comment]
Hi @denisflorkin,

The current state of the boilerplate is not ment for that kind of "hosting", i think you would need to change prod webpack config or create your own webpack.serverless config for example so your html file would also get processed with all of the assets needed for bundle to work.

In terms of serving the static html from the php server this would already be a complete fit. Its just you would need to server the same file for any requested url, and let react router decide if it matches any of the component routes.

I think this pull request would be interesting for you to take a look at: https://github.com/ctrlplusb/react-universally/pull/119/files

**Comment by denisflorkin** [comment]
Hi @EugeneHlushko,

thanks for the quick response. 
The PR you point to seems to be a excellent starting point, I'll look into it.

**Comment by EugeneHlushko** [comment]
Closing this question for now.
