### ISSUE TITLE
upgrade to webpack2

### ISSUE THREAD

**Issue by iam4x** [iam4x/isomorphic-flux-boilerplate#479]
Now in release candidate, been using for months now it's all good 👍

**Comment by jchapple** [comment]
Is this working at all? Would be cool to make use of tree shaking, if possible?

**Comment by EugeneHlushko** [comment]
Its perfectly working, if i find time will contribute. There isnt too much to do

**Comment by EugeneHlushko** [comment]
#531 is open, will try to finish it in a good timespan

**Comment by EugeneHlushko** [comment]
its in! 🎉
