### ISSUE TITLE
Question: Does alt resolver handle resolving or promises from nested components?

### ISSUE THREAD

**Issue by nim23** [iam4x/isomorphic-flux-boilerplate#48]
I have been looking at the code base and just wanted to ask if ```altResolver``` can handle resolving of promises from child components and not only the top level/handler components.

**Comment by iam4x** [comment]
No, it's not possible to have this behaviour with the current state of the boilerplate or we would need to render more than twice the application. Adjust to your needs.

But I recommend to resolve needed promises before even trying to render the application, for instance an application where you need a session I suggest you to resolve the session before routing and injecting the session in the correct store.

In `server/router.jsx`:

```
...

  // Save client cookie request headers
  // for external api calls on server side render
  flux
    .getActions('session')
    .saveCookie(this.request.headers.cookie);

  // Resolve session before rendering
  yield flux
    .getActions('session')
    .getCurrentUser();

  // Render content
  const handler = yield promisify(router.run);
  const content = yield flux.render(handler);

....
```

If more people need an example I will publish an example.

**Comment by nim23** [comment]
Thanks for the reply. I think I may have misunderstood the solution. Please correct me if I am wrong:

```
<TopLevelWrapper> //Just a wrapper
    <MainContent/> //Does a fetch
   <SideBarContent/> //Does a fetch
</TopLevelWrapper>

```
For the above example I am guessing because the ```<TopLevelWrapper/>``` does not do any fetch, but the ```<Sidebar/>``` and ```<MainContent/>```  does do a fetch, on server side the Views are only rendered once the data fetch requests for ```<MainContent/>``` and ```<Sidebar/>``` is done.

**Comment by iam4x** [comment]
Yes @nim23

**Comment by cranesandcaff** [comment]
Where should an API be put? I would find an example valuable.

**Comment by iam4x** [comment]
@cranesandcaff You can put it in the server directory, add a koajs middleware to route `/api` endpoint to your API.
