### ISSUE TITLE
socket.io or REST api?

### ISSUE THREAD

**Issue by jaulz** [iam4x/isomorphic-flux-boilerplate#5]
Any thoughts about how to integrate any of the both?

**Comment by iam4x** [comment]
For usage with socket.io, I would recommend reading: https://blog.rotenberg.io/million-user-webchat-with-full-stack-flux-react-redis-and-postgresql/

**Comment by jaulz** [comment]
Thanks for the link but I'm actually struggling where to exactly I should implement the API itself. Would you recommend to start a second project only for the API?

**Comment by iam4x** [comment]
I'm actually re-writing the part of AltResolver and services, to have a more "flux way" of doing it.

**Comment by iam4x** [comment]
With the new `alt-resolver` (#8) you can achieve easily the two possibilities: 

```
fetch() {
  if (process.env.BROWSER) {
    // fire xhr request
  }
  else {
    // retrieve users from database on the server
    const UserModel = require('user-model.js');
    users = UserModel.all();
  }
}
```

With UglifyJS well configured it will drop the condition as we build scripts for browser with `process.env.BROWSER` set to true.

**Comment by tsm91** [comment]
So basically we have to make a separate node server as an api? Is there any way to simply ignore `/api` routes with react-router?

**Comment by iam4x** [comment]
@tsm91 you can: https://github.com/iam4x/isomorphic-flux-boilerplate/issues/45#issuecomment-100284160

**Comment by tsm91** [comment]
aaaa the middleware stack, i was putting api routes after react-router ;)

**Comment by tsm91** [comment]
@iam4x i can't seem to get socket.io work while running webpack, i mean i constantly see the socketio pollings from browsersync and webpack probably. 

any idea for that?

**Comment by iam4x** [comment]
I don't have any experience with socket.io sorry, but maybe would help: https://github.com/webpack/webpack-dev-server/issues/76

**Comment by tsm91** [comment]
Yep i've tried that, the original problem is, webpack-dev-server's socket connection is on the default  [path](http://socket.io/docs/server-api/#server#path(v:string):server).
[Browsersync](http://www.browsersync.io/docs/options/#option-socket) have done this right by the way, and on top of that it even gives configuration options.

As [mentioned here](https://github.com/webpack/webpack-dev-server/issues/76#issuecomment-99005730) `io({path: '/custom/path'})` will make socket.io to connect to `window.location.href ` + the `path` specified, in my case `http://localhost:3002/custom/path` which normally would solve the problem however its not, it still picks up webpack-dev-server's emitted events, i think i wont implement socket.io for now xd
