### ISSUE TITLE
how to resolve promises only once?

### ISSUE THREAD

**Issue by filod** [iam4x/isomorphic-flux-boilerplate#52]
we have `first render` and `second render`, this leads 3 requests to server side when rendering:

1. first render: collect promises
2. second render: componentWillMount will be called again
3. browser render: componentWillMount will be called in browser.

how can i deal with this?

**Comment by iam4x** [comment]
At the second render, promises won't be resolved.

And yes when the app is mounting on clientside, they are resolving too. You can do this in your actions if you don't want to re-resolve the promise if you already have data you can do something like that:

```javascript
fetchUsers(force) {
  const promise = (resolve) => {
    const {users} = this.alt.getStore('users').getState();
    if (users.length === 0) {
      request.get('/users').then(response => {
        this.alt.actions.fetchSuccess(response.data);
        return resolve();
      });
    }
    else {
      // don't fetch users again we already have them in store
      return resolve();
    }
  }
}
```

**Comment by filod** [comment]
to my knowledge, at the second render, promises will be resolved after render.

**Comment by iam4x** [comment]
`componentWillMount` is called on second render, but since you send the promises to `this.alt.resolve` they won't be resolved on second render. Or it's a bug.

**Comment by filod** [comment]
thx, i'll check that

**Comment by iam4x** [comment]
I added a log into users actions `fetch` and here's the log of what's happening on the server:

```
<-- GET /
  dev locale of request: en +14s
  dev first render +0ms
  dev update page title to 'ISO-ReactJS | Users' +4ms
promise resolve
  dev second render +303ms
  dev update page title to 'ISO-ReactJS | Users' +6ms
  dev return html content +11ms
  --> GET / 200 329ms -
```

**Comment by filod** [comment]
thx a lot.
