### ISSUE TITLE
reset 

### ISSUE THREAD

**Issue by ami44** [iam4x/isomorphic-flux-boilerplate#54]
Hello

Install ok on local Win : great !
I have a reset bug : 

When i delete all profiles 
and add random profile
and show this new profile
and click "users list"
Then i must show one profile 
But i show ten new profiles !

How disable reset of profiles when i back to 'home' page

**Comment by iam4x** [comment]
It's the normal behaviour of the application, it's just an explanation of how things works. No persistence of data, faking XHR calls and using `.json` for users data.

**Comment by ami44** [comment]
Ok
