### ISSUE TITLE
Add a "debug" task

### ISSUE THREAD

**Issue by nuragic** [iam4x/isomorphic-flux-boilerplate#56]
Hi,

It would nice to have a ```npm run debug``` task that launch the dev server in debug mode.

I tried to do so using the node-inspector module, but I can't figure out why it doesn't start the server correctly.

You can see the change I made in the ```package.json``` here: https://github.com/nuragic/isomorphic-flux-boilerplate/commit/543c602e939b66b97d316d5249a241d1736fab2e

Any feedback is really appreciated. Thanks! :smile:

**Comment by iam4x** [comment]
Hello @nuragic I haven't used `node-inspector` yet, I'm good to add the command. Could you provide a PR with additional informations on the `README.md` about debug?

**Comment by nuragic** [comment]
Yeah, I'd really love to, but for now I've not been able to run the app correctly with the debugger attached... :disappointed: The Webpack server runs ok, I can debug it, but the koa server doesn't...

I get the following output:
![captura de pantalla 2015-05-26 a las 13 28 08](https://cloud.githubusercontent.com/assets/1586378/7811491/6eea256e-03ab-11e5-9c7a-f08bfa6011e6.png)

Can you please try (in your local machine) to add the npm debug task as in https://github.com/nuragic/isomorphic-flux-boilerplate/commit/543c602e939b66b97d316d5249a241d1736fab2e and tell me if you get the same result?

Thanks!

**Comment by iam4x** [comment]
I'll try that when I have some time this afternoon. Maybe want to bebug the node process of koa, try to `$ node-debug --hidden node_modules/ --nodejs='harmony' ./server/index.js`

**Comment by tsm91** [comment]
you could actually attach the inspector on the running node process if you want to debug conditional stuff and not the startup process itself, otherwise you should use the `--debug-brk` flag

`> node-inspector`
`> lsof -i :3001`
`> kill -s USR1 <PID>`

[more info](https://github.com/node-inspector/node-inspector#2-enable-debug-mode-in-your-node-process)
