### ISSUE TITLE
Webpack assets use localhost:{port} on remote devices

### ISSUE THREAD

**Issue by masqita** [iam4x/isomorphic-flux-boilerplate#58]
This issue seems to be explained at https://gist.github.com/MrOrz/4f3da17fd73dbb4c7668
I quickly tried out the solution, but it didn't solve the problem right away. I'll probably look into this myself one of the coming days and send you a PR, or at least try to.

It's quite easy to reproduce:
1. Start the dev server
2. Use a remote device to go to the external ip mentioned in the BrowserSync output
3. See 404s on the webpack assets, and the base URL being localhost:{port}

**Comment by iam4x** [comment]
Should be fixed, working for me.

**Comment by masqita** [comment]
Thanks!

On my iMac I have both Ethernet and Wifi active causing dev-ip to return an array with two IPs.

You might want to take the first element of the dev-ip array in `dev.config.js`

```js
const HOST = process.env.C9_HOSTNAME || require('dev-ip')()[0] || 'localhost';
```

**Comment by iam4x** [comment]
Is https://github.com/iam4x/isomorphic-flux-boilerplate/commit/255e5726d5b5543439c2b898d66b39d5c8cc1120 looking for you to close the issue?

**Comment by masqita** [comment]
Yep, solved, the issue can be closed
