### ISSUE TITLE
Passing router context to services

### ISSUE THREAD

**Issue by willcodeforfoo** [iam4x/isomorphic-flux-boilerplate#6]
I'm struggling with a way to pass context from the router (e.g., current params) to services with the new promise interface. Or is there some... _fluxier_ way?

Any ideas? Thanks for all the great work on this, especially the recent updates. Is there a place of open issues we could help with?

**Comment by iam4x** [comment]
I'm actually re-writing the whole AltResolver / Services stuff for having the fluxier way of doing it :+1:

I can't right now help you, I haven't use the new `react-router` and my actual projects are still with React 0.12 :/

**Comment by willcodeforfoo** [comment]
No worries... before the Promise updates I was passing in the `params` from the router in `alt-resolver.js`:

```js
  async.map(
    toResolve,
    (service, done) => service(done, params.params, params.query),
    (err, results) => {
      let nextState = {};

      results.forEach((result) => nextState = _.assign(nextState, result));

      // All services are resolved, let's fire the callback
      return callback(JSON.stringify(nextState));
    }
  );
```

...then passing them along to the service in `services.js`:

```js
  user(done, params) {
    return request
      .get('http://example.com/api/v1/user')
      .query({userId: params.userId})
      .end((response) => {
        return done(null, {
          UserStore: {roll: response.body}
        });
      });
  },
```

Looking forward to the new resolver stuff in the meantime!

**Comment by iam4x** [comment]
@willcodeforfoo I started a new branch with the new `alt-resolver`

https://github.com/iam4x/isomorphic-flux-boilerplate/tree/new-alt-resolver

I'm going to push an example with id from router :+1:
