### ISSUE TITLE
Koa to Express

### ISSUE THREAD

**Issue by TheSpiritMolecule** [iam4x/isomorphic-flux-boilerplate#60]
Is it possible to make a concurrent branch where the source is based on express?

**Comment by TheSpiritMolecule** [comment]
Haha, it wasn't as hard as i thought, please delete this.

**Comment by cranesandcaff** [comment]
@tsm91, would you mind sharing your express version? I prefer express to koa personally.

**Comment by nim23** [comment]
@cranesandcaff The basic scaffolding is there https://github.com/nim23/simple-iso-react, was pretty easy to implement. I have tried to keep it very minimal.
