### ISSUE TITLE
trigger server restart from console

### ISSUE THREAD

**Issue by tsm91** [iam4x/isomorphic-flux-boilerplate#63]
It would be a nice feature to manually trigger a server restart from console while webpack is running. Like `rs` if you run nodemon.

**Comment by iam4x** [comment]
Is https://github.com/iam4x/isomorphic-flux-boilerplate/commit/ab089e3d1cad2dc5169f4acac213300b637f3bf3 resolving the issue?

**Comment by tsm91** [comment]
cool! yep it works

by the way you need to `debug.enable('dev')` in `dev-server.js`, just recognised non of the debug messages appear in console the comes from webpack server.

**Comment by iam4x** [comment]
I missed that, thank's :+1: 

(I still run with `$ DEBUG=dev,koa npm run dev`)

**Comment by tsm91** [comment]
maybe you could do something similar with `cp.exec` to implement the [debug feature](https://github.com/iam4x/isomorphic-flux-boilerplate/issues/56#issuecomment-107693155)?

**Comment by iam4x** [comment]
I'll try to see if I have time, I won't find useful for myself / projects for now. But nice idea!

**Comment by tsm91** [comment]
Yep, the main problem it does not work as @nuragic pointed it out. Maybe babel mess something up, anyway [we will see](https://github.com/node-inspector/node-inspector/issues/659).
