### ISSUE TITLE
react-intl：FormattedRelative always returns English

### ISSUE THREAD

**Issue by biallo** [iam4x/isomorphic-flux-boilerplate#64]
Like this:

```javascript
// Import FormattedRelative
import {IntlMixin, FormattedRelative} from 'react-intl';

// In render() 
<FormattedRelative value={Date.now() - (1000 * 60 * 60 * 24)} />
```
No matter what the current language is, it is always return 'yesterday'.

![2015-06-02 3 54 02](https://cloud.githubusercontent.com/assets/1555457/7931054/0a17b166-0940-11e5-865c-58154270a583.png)

**Comment by iam4x** [comment]
Thank's for reporting @biallo, I'll investigate.

**Comment by iam4x** [comment]
@biallo When you pass the props to the component it will work on server side:

```javascript
<FormattedRelative {...this.props} value={Date.now() - (1000 * 60 * 60 * 24)} />
```

But will still be in english when the client will render, it might be a bug with the Intl polyfill or browser implementation of Intl.

I have to experiment with different browsers.

**Comment by biallo** [comment]
It's really a thorny issue...
So, it is possible to find a solution?

**Comment by erkieh** [comment]
A similar bug on react-intl: https://github.com/yahoo/react-intl/issues/114

**Comment by linsong1013** [comment]
@iam4x   I find a solution.
Here is my code:

1.define  ReactIntl  belong to window
2.require 'react-intl/dist/locale-data/zh.js'
![xx](https://cloud.githubusercontent.com/assets/1981242/8494702/dd2cdc18-2199-11e5-9a05-7c08c79ff3f5.jpg)

**Comment by iam4x** [comment]
@linsong1013 Whaaaat, do you have information about this?

**Comment by linsong1013** [comment]
@iam4x  I find solution here: https://github.com/yahoo/react-intl/issues/114
![image](https://cloud.githubusercontent.com/assets/1981242/8507834/676d58f6-2287-11e5-9142-a75e0e8d5f38.png)
when I load language package from 'data/xx', I also require 'react-intl/dist/locale-data/xx.js'.
I modify the file: 'app/utils/intl-loader.js'
![image](https://cloud.githubusercontent.com/assets/1981242/8507868/c5f699f4-2288-11e5-84ab-3588d2c5e143.png)

**Comment by iam4x** [comment]
I'll try it myself, I'm not sur why you have to declare on global scope `window.ReactIntl`

**Comment by iam4x** [comment]
Thank's again @linsong1013 :+1:

**Comment by linsong1013** [comment]
:+1:
