### ISSUE TITLE
Problem with CSS in dev mode

### ISSUE THREAD

**Issue by two-ya** [iam4x/isomorphic-flux-boilerplate#66]
When I start `npm run dev` and disable JS in the browser I loose styles for all elements on the page:
![screen shot 2015-06-03 at 23 17 19](https://cloud.githubusercontent.com/assets/12728040/7977772/403186d8-0a5c-11e5-93c1-995bb23e3973.png)

However demo at your web-site works good with disabled JS.

I've copied part from your prod.config.js file regarding
`loader: ExtractTextPlugin.extract('style', 'css!autoprefixer?browsers=last 2 version!sass')`
and everything starts to work properly, but I'm not familiar with webpack neither with JS and not sure it is right way to fix the problem.

**Comment by iam4x** [comment]
@two-ya Hello, in dev mode you need to use JavaScript. It will update your JS/CSS code on your webpage dynamically.

When you want to build on production, you want the CSS to be extracted in another file.
