### ISSUE TITLE
Drop `alt-resolver` use `AltIso.render`

### ISSUE THREAD

**Issue by iam4x** [iam4x/isomorphic-flux-boilerplate#68]
https://github.com/goatslacker/alt/commit/4cf98e312245d2b38952a4775fcd1e437a9d2544

* [x] Drop alt instances, come back to singleton!
* [x] Rewrite async actions with datasources from alt (http://alt.js.org/docs/async/)
* [ ] Use `AltIso.render` helper

:tada:

**Comment by quicksnap** [comment]
Think rewriting with datasources could be done independently of other tasks? I might be able to help out if so. Looking to cut my teeth on some Alt stuff; thinking of switching over to it.

**Comment by iam4x** [comment]
@quicksnap We can't use datasource with the current `alt-resolver` made for the boilerplate, these tasks need to be done together.

I'll start a new branch with `react-router@1.0-beta` and try to merge with new IsoRender from Alt, maybe it will work. For now I can't make them work together.

**Comment by jonaswindey** [comment]
I'm looking at the 'use-alt-for-render' branch. Do you have any idea what's going wring with the router? It seems you can only switch page ones, and then the router stops working.

I tried stripping out some datasources-related stuff but can't get it to work.

**Comment by jonaswindey** [comment]
I think I found it,

in main.js

```
Router.run(
  routes,
  Router.HistoryLocation,
  (Handler) => AltIso.render(alt, Handler)
);
```

Should become:
```
Iso.bootstrap(function (state, _, container) {
  alt.bootstrap(state);

  Router.run(routes, Router.HistoryLocation, function (Handler) {
    var node = React.createElement(Handler);
    React.render(node, container);
  });
});
```

**Comment by iam4x** [comment]
@jonaswindey I'm waiting for https://github.com/goatslacker/alt/pull/364 to be merged and new Alt released :+1:

Right now nested components won't have its datasources resolved, so when App fetches locale which is our root component nothing else will be resolved.

**Comment by iam4x** [comment]
It's not in the scope of Alt anymore, will keep our internal solution.
