### ISSUE TITLE
React checksum warning when using `style` prop on components

### ISSUE THREAD

**Issue by bshyong** [iam4x/isomorphic-flux-boilerplate#73]
When I use a `style` prop on a component, React throws a warning:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) sten Wiig Movie HD" style="width:50vw;he
 (server) sten Wiig Movie HD" data-reactid=".18afr
```

It looks like the style prop is only rendered on the client side.  Any idea how I can fix this? I want to be able to style a component directly, instead of having to add CSS rules in another file.

**Comment by iam4x** [comment]
On dev mode, koa server won't restart and cache the files until you change a server file (in directory `/server`) or by typing `rs` in the terminal.

Have you tried to restart the koa server after changing a component when you have this message?

**Comment by claym** [comment]
closing and opening a new browser/tab usually makes this go away for me.

**Comment by bshyong** [comment]
Thanks guys!
