### ISSUE TITLE
Better docs - specifically views / actions / stores

### ISSUE THREAD

**Issue by claym** [iam4x/isomorphic-flux-boilerplate#74]
I'm slowing working through this, but we could really use a little more documentation on how to wire up new actions, views and stores.

The approach in the boilerplate diverges enough from the basic alt docs that it's really difficult to figure out what's going on.

I've successfully wired up a new set, but I don't understand it well enough to 1) feel secure that i've done it right and 2) do the documentation myself

For example, I know I need to add this to my view to access this.setState

_handleStoreChange = this._handleStoreChange.bind(this);

but I have no idea why :)

The docs on async data fetching is great, so more of that type of thing would be great.

A step by step guide to adding a new action, store and view would be good. Items like "make sure you add them both to utils/flux.js"

Additionally, I have no idea what the request store is supposed to be doing :)

Anyway, this is the best boilerplate I've found, so keep up the good work!

**Comment by iam4x** [comment]
Hello @claym lot of stuff will change with the new API of `react-router@1.0` and with the new `AltIso.render` (see #69).

I won't move the docs until I have a new version with updated libs, it will certainly change most of the logic of the boilerplate.

But I totally agree that we need more guides, examples and robust documentation :+1: 

Thank's for the message :)

**Comment by EugeneHlushko** [comment]
Hello @iam4x , when do you think we can see a new version with updated libs?

**Comment by iam4x** [comment]
@EugeneHlushko I have no idea, I have to give it a try with `react-router@1.0-beta` but I'm very busy at work this last days. I will may have some time next week :+1: 

The boilerplate is working great at current state anyway, we use it in production @ savemysmartphone.com (not on the actual website but internal tools)

**Comment by EugeneHlushko** [comment]
Well you see @iam4x i was making a test-app with your boilerplate and now ended up with React.addons.CSSTransitionGroup problems caused by RouteHandler in react-router versions below 1.0.0

I hope i can re-write router logic within new version of react router myself, but i hope you will get your hands on it soon :+1:

**Comment by iam4x** [comment]
@EugeneHlushko Have you tried the TransitionGroup? https://github.com/rackt/react-router/issues/1116

**Comment by EugeneHlushko** [comment]
@iam4x yeah, it works fine within pages child elements (e.g. list of items or etc), but i cannot "transition" a whole page after link click, here is what i try in app js and it is not working:

```
render() {
    const props: Object = assign({}, this.state, this.props);
    return (
      <div>
        <Header {...props} />
        <Transition component="div" transitionName="hugeAnim" transitionAppear={true} transitionLeave={false}>
          <RouteHandler {...props} key={this.props.pathname} />
        </Transition>
        <Footer />
      </div>
    );
  }
```

And for instance a working example of fade-in list items:

```
render() {
    debug('dev')('will render the component, and items are', this.state.items);
    return (
      <div>
        <h1>Protected</h1>
        <ReactCSSTransitionGroup component="div" transitionName="fadeIn" transitionAppear={true} transitionLeave={false}>
          <Gmapitem items={this.state.items} clickHandler={this._remove}/>
        </ReactCSSTransitionGroup>
        <div id="gmap"></div>
      </div>
    );
  }
```

**Comment by iam4x** [comment]
Thank's for example, I've created another issue for react-router #77

**Comment by claym** [comment]
Oh one thing that never got addressed - what is the "requests" actions and store for?



-Clay

**Comment by iam4x** [comment]
@claym Look: https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/app%2Fcomponents%2Fshared%2Fspinner.jsx

I use these two to show / hide a spinner on requests. It was fast written, maybe not the best way to achieve it but it works for example.
