### ISSUE TITLE
Reduce .bind(this) by using arrow functions

### ISSUE THREAD

**Issue by jonaswindey** [iam4x/isomorphic-flux-boilerplate#81]
In the components, there is a lot of redundant boilerplate, like:
```
_handleLocaleChange = this._handleLocaleChange.bind(this)
_handleLocaleChange(state: Object) {
    return this.setState(state);
}
``` 
This is not only a duplicate method definition (according to Webstorm), but it can be written shorter like this:
```
_handleLocaleChange = (state: Object) => {
    this.setState(state);
}
``` 
Is there a reason for choosing the other syntax? The power of arrow functions is that we don't need to bind(this) every time.

Also, is there a reason to return this.setState instead of just calling this.setState and returning nothing?

**Comment by iam4x** [comment]
I use now with babel stage 0, it's just preference you can use what ever you want.

```javascript
_handleLocaleChange = ::this._handleLocalChange
_handleLocaleChange() {
  [...]
}
```


I prefere to have implicit method for updating state from store change, some time I need more logic.
And for `store.unlisten` you need to give the function which was listening.

**Comment by jonaswindey** [comment]
Is that double colon an ES7 feature?

**Comment by iam4x** [comment]
Yes https://github.com/zenparsing/es-function-bind
