### ISSUE TITLE
How to debug in Chrome

### ISSUE THREAD

**Issue by jonaswindey** [iam4x/isomorphic-flux-boilerplate#82]
Is is possible to put breakpoints in stores and components?

Before, I used another react starterkit (webpack-react) and there I could just open every file in developer tools with cmd-o and access a store or an action or whatever.

It seams it's only possible to put breakpoints in the whole generated app.js? Do we need to configure sourcemaps to allow this?

**Comment by iam4x** [comment]
There's an issue with chrome breakpoints and sourcemap when link the folder look:  https://github.com/webpack/webpack/issues/613

**Comment by jonaswindey** [comment]
Take a look at este: https://github.com/steida/este , there debugging/breakpoints in Chrome work for both views, stores, etc.
