### ISSUE TITLE
Data fetch requests called multiple times

### ISSUE THREAD

**Issue by imouto1994** [iam4x/isomorphic-flux-boilerplate#84]
For the current implementation, are the data fetching requests called multiple times (2 times on the server-side for 2 phases of render and 1 time when the client is first loaded ) ? Is it intended ? Is there any way to prevent this ?

**Comment by dmitry** [comment]
You have to check store if it already filled with a data or no. You data `id` must be checked too, if your storage can have different records depending on parameters.

**Comment by imouto1994** [comment]
Can you evaluate your solution further ? 
If I only check if the store is filled with data or not, I cannot refetch the data when I change route. What I need is only to prevent refetching data for initial load

**Comment by dmitry** [comment]
The same code invoked in `componentWillReceiveProps` and `componentDidMount`.

```javascript
if (this.state.user.id !== parseInt(params.userId, 10)) {
  this.props.flux.getActions('user').fetch(this.getParams()); // getParams is from `Router.State` mixin
}
```

**Comment by imouto1994** [comment]
This solution might not solve all cases such as when I want to fetch a list of data instead of a specific data `id`.

**Comment by dmitry** [comment]
@imouto1994 in that case you have to save parameters that you are passing to get the list. You can store parameters in the store in the component (which is less preferable, because of possible inconsistency).

**Comment by imouto1994** [comment]
I think this might not be the correct behavior. Basically, everytime you change route, you still want to refetch new data. The only time that you want to avoid refetching is the first time you load the page on client side since the data has already been fetched in server side.
So I think avoding refetching by checking `id` or `params` here is not correct

**Comment by dmitry** [comment]
@imouto1994 
> everytime you change route, you still want to refetch new data

Proposed solution will solve this aswell.

**Comment by imouto1994** [comment]
@dmitry Sorry then can you elaborate more on your solution ? Since I cannot see how you can distinguish between the first time you handle the routing callback on client side and the subsequent callbacks

**Comment by dmitry** [comment]
Save values of `this.getParams()` in store, when you are passing it (as in example) to `fetch`.

```javascript
export default class UserActions {
  constructor() {
    this.generateActions(
      'success',
      'error',
      'reset'
    );
  }
  fetch(params) {
   if (this.alt.getStore('user').params !== params) {
     request(params, (user) => {
       this.actions.success({user, params});
     });
   }
  }
)
```

In your store:

```javascript
export default class UserStore {
  constructor() {
    this.bindActions(this.alt.getActions('user'));
    this.user = {};
    this.params = {};
    this.error = null;
  }

  onSuccess(data) {
    this.setState(data);
  }
}
```

**Comment by imouto1994** [comment]
@dmitry Then for example, assuming in the route `/home` I will fetch new data from users. Hence, for everytime I go back to this route, I will want to fetch for new data. 
If I follow your solution, it will not fetch for new data due to their is no parameters

**Comment by dmitry** [comment]
@imouto1994 in that case I still don't know what to do. May be @iam4x can help us!? :)

**Comment by iam4x** [comment]
At SSR promises will be resolved only once, so the data will be fetched once.

But when the APP mount on client-side, you are right data will be re-fetched / updated. I have an idea how to fix this.

**Comment by dmitry** [comment]
@iam4x thanks for the fix. Will it work after the https://github.com/iam4x/isomorphic-flux-boilerplate/pull/69 will be merged?

**Comment by iam4x** [comment]
@dmitry This is a workaround until #69 is merged :+1: Alt is handling it correctly when I tested it :+1:

**Comment by imouto1994** [comment]
@iam4x I think this fix will be incorrect if there are multiple fetch requests for a route ? Correct me if I am wrong

**Comment by dmitry** [comment]
@imouto1994 have you checked this behavior?

**Comment by iam4x** [comment]
@imouto1994 You are right, imho it would be overkill to flag promises that has been resolved with an ID or something, store them in a Alt Store and cancel them if they are sent from client on first rendering.

I prefer to wait for `AltIso.render` PR to be merged which will handle this correctly.

**Comment by imouto1994** [comment]
Ok, I also agree to wait for the new render approach from `Alt`
In the mean time, the way I solve this is to keep track the number of components having fetching requests for every route change :)

**Comment by jchapple** [comment]
The other problem with commit https://github.com/iam4x/isomorphic-flux-boilerplate/commit/fd81eb46831039f28f52aa2473f765ed89d746f2 is that if you land on a route that has no promises to resolve and then navigate to a different route with promises to resolve, the resolver will `noop` rather than attempting to any resolve promises.

**Comment by iam4x** [comment]
Should resolve the multiple requests on a route and the problem you pointed out @jchapple :+1:

**Comment by jchapple** [comment]
Thanks, works great! :+1:

**Comment by iam4x** [comment]
Great!

**Comment by imouto1994** [comment]
@iam4x Nice solution ! :+1: Thanks :)
