### ISSUE TITLE
Babel is not a devDependencies

### ISSUE THREAD

**Issue by mercuriete** [iam4x/isomorphic-flux-boilerplate#85]
babel is needed when you require it on the server.

server/index.js

line 10
// Install `babel` hook for ES6
require('babel/register');

if you previously do a npm prune --production in order to delete all unneeded libraries....
you delete babel as well because is in devDependencies.

maybe i am missing something.

thanks in advance.

edited:

i fix that issue moving babel to the devDependencies.

But now i have a question:

Are there any way to pack the server side application with webpack in order to dont depend on babel?

thanks

**Comment by iam4x** [comment]
You are right, moving them into `dependencies`

**Comment by mercuriete** [comment]
im not sure. im new in nodejs world. but i was thinking in dont have babel as a dependency but a devdependency and still have ecma 6 syntax on server side.

and as side effect, a bundle javascript run faster because the interpreter dont need to read too much.
I'm not sure if this makes sense xD.

Thanks, and you can close this bug.
