### ISSUE TITLE
Small image files

### ISSUE THREAD

**Issue by lovegroveandy** [iam4x/isomorphic-flux-boilerplate#87]
There seems to be an issue when I add an image whose file size is less than the 10k limit specified in the webpack prod-config. The url encoding is fine but an entry is still created in the webpack-stats.json with a filename of undefined. If I then disable javascript in the browser I get a broken image link.

If I reduce the threshold of the limit url?limit=1000&name=[sha512:hash:base64:7].[ext] then the file is created and loads without issue.

So it would seem that if we are under the file size limit then we don't need an entry in the webpack-stats.json file as we will be using base64? I could of course be misunderstanding the implementation.

**Comment by cridenour** [comment]
I've noticed this behavior as well. Might need an update to webpack/utils/write-stats.js to handle the URL encoded images. For now, I just switched to file-loader.

**Comment by iam4x** [comment]
@cridenour you are right, the case is not handled yet. I'll try to find a way.
