### ISSUE TITLE
My bundle gets bigger and bigger. (question)

### ISSUE THREAD

**Issue by mercuriete** [iam4x/isomorphic-flux-boilerplate#88]
My bundle are getting bigger and bigger every time i add a new library to my dependencies.

for example: this morning my app was about 700 KB but then i add momentJS to my dependencies.

as webpack automatically pack everything, now it grows to 900KB and its starting to be undesirable.

The server rendering is fast but the delivering this app to the client is slow so there are a long time from the browser gets the html and the app re-render the aplication.

I was reading about chunking in webpack but im not sure if this solves the problem.

Webpack sould be smart enough to clean the dead code or the code that never gets executed.

Thank you in advance.

**Comment by dmitry** [comment]
Just include this code to ignore locale files. 

```javascript
webpack: {
    module: {
      noParse: [/moment\.js/]
    }
}
```

Also webpack have a nice feature `--stats --json > stats.json` when bundling. It creates stats, which then can be analyzed with http://webpack.github.io/analyse/ Very nice tool, that gives you detailed view of what can slow/grow your application.

**Comment by mercuriete** [comment]
thanks so much for your answer.

i am looking this analysis tool and is amazing.

i will check the webpack documentation in order to understand the noParse argument.

anyway i realized that my bundle is compressed when is delivered with the koa server so the size that chrome says that my bundle has is smaller. usually a 800 KB bundle is reduced to 200 KB only with this compression.

thank you again :)

**Comment by dmitry** [comment]
@mercuriete don't forget about gzip. 200kb for modern application is good size for javascript code.

**Comment by iam4x** [comment]
Thanks for helping out @dmitry :+1:
