### ISSUE TITLE
require-auth working?

### ISSUE THREAD

**Issue by lovegroveandy** [iam4x/isomorphic-flux-boilerplate#89]
I was just wondering if this aspect of the project was working as I can't seem to get the transition to show please log in? It would be great to see an example of how this can be wired up as I have added a auth store and action but can't seem to get it running.

OK building on this I see that in the react-router beta version used in this project the willTransitionTo that is used has been dropped. The update is an onEnter method that is applied directly to the route it would seem. You do all this hard work and the rug kinda gets pulled under you eh? :)

**Comment by iam4x** [comment]
@lovegroveandy It was working with react-router@0.13, since I've updated the boilerplate to a beta it's not ready yet.

**Comment by lovegroveandy** [comment]
@iam4x I figured that would be the case. Having seen your update to the routes.js I guess it would be a case of adding something along the lines of:
{generateRoute({
      paths: ['/protected', '/protege'],
      component: require('./components/protected'),
      onEnter: requireAuth
    })}

Where requireAuth would be a function that checks login state and performs a transition.to if the user is not logged in?

I'm trying to implement this although I'm struggling to work out how to check login status from the routes.js assuming an auth store. Any ideas at all?

**Comment by iam4x** [comment]
@lovegroveandy Right now it's not possible to have it run on the server side, I'll push you a commit where it works on client side.

**Comment by iam4x** [comment]
https://github.com/iam4x/isomorphic-flux-boilerplate/commit/f46ac117fd7400ce3ee5ecfe935887c4d3a43411

**Comment by lovegroveandy** [comment]
Thanks for your help Maxime, I'll keep an eye on the issue with react-router

**Comment by iam4x** [comment]
Should be good now @lovegroveandy :+1:
