### ISSUE TITLE
updating to Intl 1.0.0   require('intl/Intl');  does not exist

### ISSUE THREAD

**Issue by mercuriete** [iam4x/isomorphic-flux-boilerplate#91]
I recently update to the latest Intl 1.0.0 library and now webpack complaints in this line:

https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/app/utils/intl-loader.js#L17

        require('intl/Intl');

I fix it this problem changing all these lines to

        require('intl');

but im not sure if this is the correct way.

I create this bug for the people that are using your boilerplate and then update some libraries.

Thanks for creating this awsome boilerplate.

**Comment by iam4x** [comment]
@mercuriete Thank's didn't take enough time on updating `intl` since it works great with current version.

I'll try your solution :+1:

**Comment by iam4x** [comment]
In master :tada:
