### ISSUE TITLE
What module are you using for requests?

### ISSUE THREAD

**Issue by lolJS** [iam4x/isomorphic-flux-boilerplate#95]
@iam4x What are you using to make requests in your snippet?
```
fetch() {
  const promise = (resolve) => {
    request
      .get('http://example.com/api/users')
      .end((response) => {
        // fire new action to send data to store
        this.actions.fetchSuccess(response.body);
        return resolve();
      });
  };
  // Send the `promise` to altResolver
  this.alt.resolve(promise);
}
```
I've tried a couple of modules and can't seem to make it work it just hangs hitting my api end point.

**Comment by iam4x** [comment]
This example isn't running with a library to make requests, you can use any isomoprhic library like:

* https://github.com/mzabriskie/axios
* https://github.com/visionmedia/superagent
* https://github.com/request/request
* https://github.com/matthew-andrews/isomorphic-fetch

Here's an API Client / Helper example I made for another boilerplate: https://github.com/savemysmartphone/universal-redux-boilerplate/blob/master/shared/api-client.js

**Comment by lolJS** [comment]
Axios didn't seem to work out. I was trying to send the promise from axios directly to alt-resolve. SuperAgent worked our great though. Thanks for the speedy response.

**Comment by iam4x** [comment]
Cool :)
